export const courseList = [
  {
    faculty_id: 1,
    faculty_name: "Natural and Agricultural Sciences",
    faculty_abreviation: "NAS",
    description: "Faculty of Natural and Agricultural Sciences",
    courses: [
      { id: 0, course_name: "Dip IN INFO AND COMM TECH APP DEV", course_code: "ICT602" },
      { id: 1, course_name: "DIPLOMA IN AGRICULTURE", course_code: "AGR600" },
      { id: 2, course_name: "BSc IN DATA SCIENCE", course_code: "BSC702" },
      { id: 3, course_name: "BSC MATHEMATICAL AND COMPUTER SCIENCES", course_code: "BSC706" },
      { id: 4, course_name: "BSc BIOLOGICAL SCIENCES", course_code: "BSC708" },
      { id: 5, course_name: "BSc PHYSICAL SCIENCE: GEOGRAPHY", course_code: "BSC765" },
      { id: 6, course_name: "BSc PHYSICAL SCIENCE: CHEMISTRY STREAM", course_code: "BSC763" },
      { id: 7, course_name: "BSc PHYSICAL SCIENCE: CHEMISTRY STREAM", course_code: "BSC761" },
      { id: 8, course_name: "BSc PHYSICAL SCIENCES: PHYSICS STREAM", course_code: "BSC764" },
    ],
  },
  {
    faculty_id: 2,
    faculty_name: "Education",
    faculty_abreviation: "EDU",
    description: "Faculty of Education",
    courses: [
      { id: 0, course_name: "BEd FOUNDATION PHASE TEACHING", course_code: "EDU720" },
      { id: 1, course_name: "BEd LANG MATHS NATURAL SCIENCES & TECH", course_code: "EDU723" },
      { id: 2, course_name: "BED LANG SOCIAL SCIENCES & LIFE SKILLS", course_code: "EDU724" },
      { id: 3, course_name: "BED LIFE SCIENCE NATURAL SCIENCE TEACH", course_code: "EDU731" },
      { id: 4, course_name: "BEd LANGUAGES AND HISTORY TEACHING", course_code: "EDU734" },
      { id: 5, course_name: "BED HISTORY SOCIAL SCIENCE & LANG TEACH", course_code: "EDU735" },
      { id: 6, course_name: "BEd TEACH OF ACC ECO BUS SC MANAGEMENT", course_code: "EDU738" },
      { id: 7, course_name: "Adv DIP IN SCHOOL LEADERSHIP & MAMAGEMENT", course_code: "ELM700" },
    ],
  },
  {
    faculty_id: 3,
    faculty_name: "Economic and Management Sciences",
    faculty_abreviation: "EMS",
    description: "Faculty of Economic and Management Sciences",
    courses: [
      { id: 0, course_name: "BCom IN ACCOUNTING", course_code: "BCA701" },
      { id: 1, course_name: "BCOM IN ECONOMICS", course_code: "BCE701" },
      { id: 2, course_name: "DIP IN RETAIL BUSINESS MANAGEMENT", course_code: "RBM601" },
    ],
  },
  {
    faculty_id: 4,
    faculty_name: "Humanities",
    faculty_abreviation: "HUM",
    description: "Faculty of Humanities",
    courses: [
      { id: 0, course_name: "BA - GENERAL", course_code: "BAG701" },
      { id: 1, course_name: "HCERT IN COURT INTERPRETING", course_code: "HCI500" },
      { id: 2, course_name: "HCERT IN HERITAGE STUDIES", course_code: "HER501" },
    ],
  },
];

export const facultiesDataList = [
  {
    faculty_id: 1,
    faculty_name: "Natural and Applied Sciences",
    faculty_abreviation: "NAS",
    description: "Faculty of Natural and Agricultural Sciences",
    courses: [
      { id: 0, course_name: "Dip IN INFO AND COMM TECH APP DEV", course_code: "ICT602" },
      { id: 1, course_name: "DIPLOMA IN AGRICULTURE", course_code: "AGR600" },
      { id: 2, course_name: "BSc IN DATA SCIENCE", course_code: "DSC702" },
      { id: 3, course_name: "BSc MATHEMATICAL AND COMPUTER SCIENCES", course_code: "BSC706" },
      { id: 4, course_name: "BSc BIOLOGICAL SCIENCES", course_code: "BSC708" },
      { id: 5, course_name: "BSc BIOLOGICAL SCIENCES", course_code: "BSC708" },
      { id: 6, course_name: "BSc PHYSICAL SCIENCES: GEOLOGY", course_code: "BSC766" },
      { id: 7, course_name: "BSc PHYSICAL SCIENCES: GEOGRAPHY", course_code: "BSC765" },
      { id: 8, course_name: "BSc PHYSICAL SCIENCES: CHEMISTRY STREAM", course_code: "BSC763" },
      { id: 9, course_name: "BSc PHYSICAL SCIENCES: CHEMISTRY STREAM", course_code: "BSC761" },
      { id: 10, course_name: "BSc PHYSICAL SCIENCES: PHYSICS STREAM", course_code: "BSC764" },
      { id: 11, course_name: "BESc (BACHELOR OF ENVIROMENTAL SCIENCE)", course_code: "ENV800" },
    ],
  },
  {
    faculty_id: 2,
    faculty_name: "Education",
    faculty_abreviation: "EDU",
    description: "Faculty of Education",
    courses: [
      { id: 0, course_name: "BEd FOUNDATION PHASE TEACHING", course_code: "EDU720" },
      { id: 1, course_name: "BEd LANG MATHS NATURAL SCIENCES & TECH", course_code: "EDU723" },
      { id: 2, course_name: "BED LANG SOCIAL SCIENCES & LIFE SKILLS", course_code: "EDU724" },
      { id: 3, course_name: "BED LIFE SCIENCE NATURAL SCIENCE TEACH", course_code: "EDU740" },
      { id: 4, course_name: "BEd LANGUAGES AND HISTORY TEACHING", course_code: "EDU734" },
      { id: 5, course_name: "BED HISTORY SOCIAL SCIENCE & LANG TEACH", course_code: "EDU735" },
      { id: 6, course_name: "BEd TEACH OF ACC ECO BUS SC MANAGEMENT", course_code: "EDU738" },
      { id: 7, course_name: "Adv DIP IN SCHOOL LEADERSHIP & MAMAGEMENT", course_code: "ELM700" },
    ],
  },
  {
    faculty_id: 3,
    faculty_name: "Economic and Management Sciences",
    faculty_abreviation: "EMS",
    description: "Faculty of Economic and Management Sciences",
    courses: [
      { id: 0, course_name: "BCom IN ACCOUNTING", course_code: "BCA701" },
      { id: 1, course_name: "BCom IN ECONOMICS", course_code: "BCE701" },
      { id: 2, course_name: "Dip IN RETAIL BUSINESS MANAGEMENT", course_code: "RBM601" },
      { id: 3, course_name: "HCert IN ENTREPRENEURSHIP", course_code: "MEN500" },
    ],
  },
  {
    faculty_id: 4,
    faculty_name: "Humanities",
    faculty_abreviation: "HUM",
    description: "Faculty of Humanities",
    courses: [
      { id: 0, course_name: "BA - GENERAL", course_code: "BAG701" },
      { id: 1, course_name: "HCert IN COURT INTERPRETING", course_code: "HCI500" },
      { id: 2, course_name: "HCert IN HERITAGE STUDIES", course_code: "HER501" },
    ],
  },
];
