export const departmentsList = [
  {
    faculty: "Office of the Vice-Chancellor",
    type: "Executive",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Office of the Vice-Chancellor",
        description: "Strategic leadership and overall university governance.",
        positions: [
          { id: 0, title: "Vice-Chancellor" },
          { id: 1, title: "Deputy Vice-Chancellor: Academic" },
          { id: 2, title: "Deputy Vice-Chancellor: Research and Innovation" },
          { id: 3, title: "Deputy Vice-Chancellor: Institutional Support" },
          { id: 4, title: "Executive Director" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Executive Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Registrar's Office",
        description: "Manages academic administration, examinations, and student records.",
        positions: [
          { id: 0, title: "Registrar" },
          { id: 1, title: "Deputy Registrar" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Manager" },
          { id: 4, title: "Senior Administrator" },
          { id: 5, title: "Administrator" },
          { id: 6, title: "Records Officer" },
          { id: 7, title: "Examinations Officer" },
          { id: 8, title: "Administrative Assistant" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Institutional Planning and Quality Assurance",
        description: "Leads strategic planning, data analytics, and academic quality monitoring.",
        positions: [
          { id: 0, title: "Director: Institutional Planning" },
          { id: 1, title: "Director: Quality Assurance" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Manager" },
          { id: 4, title: "Quality Assurance Officer" },
          { id: 5, title: "Research Analyst" },
          { id: 6, title: "Data Administrator" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "NAS",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Mathematics and Statistics",
        description: "Mathematical theory, applied mathematics, and statistics.",
        positions: [
          { id: 0, title: "Dean" },
          { id: 1, title: "Deputy Dean" },
          { id: 2, title: "Head of Department" },
          { id: 3, title: "Professor" },
          { id: 4, title: "Associate Professor" },
          { id: 5, title: "Senior Lecturer" },
          { id: 6, title: "Lecturer" },
          { id: 7, title: "Researcher" },
          { id: 8, title: "Manager" },
          { id: 9, title: "Senior Manager" },
          { id: 10, title: "Tutor" },
          { id: 11, title: "Administrator" },
          { id: 12, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Computer Science",
        description: "Software engineering, programming, and data science.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Lab Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Teaching Assistant" },
          { id: 9, title: "Administrator" },
          { id: 10, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Physics",
        description: "Matter, energy, and physical sciences.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Laboratory Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Chemistry",
        description: "Chemical reactions, materials, and molecular research.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Research Assistant" },
          { id: 5, title: "Laboratory Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 5,
        name: "Biological Sciences",
        description: "Life sciences, genetics, and environmental biology.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Lab Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 6,
        name: "Geography and Environmental Science",
        description: "Earth systems, GIS, and climate studies.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "GIS Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "EDU",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Educational Studies",
        description: "Education theory, leadership, and management.",
        positions: [
          { id: 0, title: "Dean" },
          { id: 1, title: "Deputy Dean" },
          { id: 2, title: "Head of Department" },
          { id: 3, title: "Professor" },
          { id: 4, title: "Senior Lecturer" },
          { id: 5, title: "Lecturer" },
          { id: 6, title: "Researcher" },
          { id: 7, title: "Manager" },
          { id: 8, title: "Senior Manager" },
          { id: 9, title: "Administrator" },
          { id: 10, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Foundation Phase Teaching",
        description: "Teaching methodologies for early childhood and primary education.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Lecturer" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Tutor" },
          { id: 4, title: "Teaching Assistant" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Language and Social Sciences Education",
        description: "Languages, history, and social science education.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Lecturer" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Researcher" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Tutor" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Mathematics, Science and Technology Education",
        description: "STEM-focused teaching and learning development.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Tutor" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "EMS",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Accounting",
        description: "Financial and management accounting education and research.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Economics",
        description: "Economic theory, econometrics, and applied economics.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Business Management",
        description: "Leadership, entrepreneurship, and organizational management.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Public Administration",
        description: "Governance, public policy, and administrative systems.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Senior Lecturer" },
          { id: 2, title: "Lecturer" },
          { id: 3, title: "Researcher" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "HUM",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Languages and Communication",
        description: "Linguistics, translation, and media communication.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Psychology",
        description: "Human behavior, cognitive science, and counselling.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Psychologist" },
          { id: 5, title: "Researcher" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Sociology and Anthropology",
        description: "Social theory, human culture, and society.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "History and Heritage Studies",
        description: "Historical research, heritage preservation, and cultural studies.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Lecturer" },
          { id: 2, title: "Researcher" },
          { id: 3, title: "Curator" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "ICT",
    type: "Administrative",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Information and Communication Technology",
        description: "Digital infrastructure, systems support, and information management.",
        positions: [
          { id: 0, title: "Chief Information Officer" },
          { id: 1, title: "Director: ICT Services" },
          { id: 2, title: "Senior Manager: Infrastructure" },
          { id: 3, title: "ICT Manager" },
          { id: 4, title: "Network Administrator" },
          { id: 5, title: "Systems Analyst" },
          { id: 6, title: "Database Administrator" },
          { id: 7, title: "ICT Technician" },
          { id: 8, title: "Support Officer" },
          { id: 9, title: "Administrator" },
          { id: 10, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "Finance",
    type: "Administrative",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Finance Department",
        description: "Manages university finances, budgeting, and reporting.",
        positions: [
          { id: 0, title: "Chief Financial Officer" },
          { id: 1, title: "Director: Finance" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Manager" },
          { id: 4, title: "Senior Finance Officer" },
          { id: 5, title: "Accountant" },
          { id: 6, title: "Procurement Officer" },
          { id: 7, title: "Payroll Officer" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "Human Resources",
    type: "Administrative",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Human Resources Department",
        description: "Employee recruitment, training, and welfare management.",
        positions: [
          { id: 0, title: "Executive Director: Human Resources" },
          { id: 1, title: "Director: HR" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Manager" },
          { id: 4, title: "Senior HR Officer" },
          { id: 5, title: "HR Officer" },
          { id: 6, title: "Training Coordinator" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "Library",
    type: "Administrative",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Library and Information Services",
        description: "Manages library resources and academic information access.",
        positions: [
          { id: 0, title: "Director: Library Services" },
          { id: 1, title: "Senior Librarian" },
          { id: 2, title: "Librarian" },
          { id: 3, title: "Library Assistant" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Cataloguer" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "Marketing and Communications",
    type: "Administrative",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Marketing and Communications",
        description: "Promotes university image, branding, and stakeholder communication.",
        positions: [
          { id: 0, title: "Director: Marketing and Communications" },
          { id: 1, title: "Senior Manager" },
          { id: 2, title: "Manager" },
          { id: 3, title: "Communications Officer" },
          { id: 4, title: "Marketing Officer" },
          { id: 5, title: "Graphic Designer" },
          { id: 6, title: "Photographer/Videographer" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "Student Affairs",
    type: "Administrative",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Student Support Services",
        description: "Supports student welfare, engagement, and development.",
        positions: [
          { id: 1, title: "Director: Student Affairs" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Manager" },
          { id: 4, title: "Student Counsellor" },
          { id: 5, title: "Career Development Officer" },
          { id: 6, title: "Peer Mentor" },
          { id: 7, title: "Student Affairs Officer" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Residences and Accommodation",
        description: "Manages student housing and residential life.",
        positions: [
          { id: 1, title: "Residence Warden" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Residence Manager" },
          { id: 4, title: "Residence Assistant" },
          { id: 5, title: "Administrator" },
          { id: 6, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "Legal and Compliance",
    type: "Administrative",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Legal and Compliance Services",
        description: "Ensures institutional legal compliance and governance.",
        positions: [
          { id: 1, title: "Director: Legal and Compliance" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Manager" },
          { id: 4, title: "Legal Advisor" },
          { id: 5, title: "Compliance Officer" },
          { id: 6, title: "Internal Auditor" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
    ],
  },
];

export const departmentEntitiesList = [
  {
    faculty: "Office of the Vice-Chancellor",
    type: "Executive",
    description: "Central executive authority responsible for strategic leadership and institutional oversight.",
    departments: [
      {
        id: 1,
        name: "Office of the Vice-Chancellor",
        description: "Overall leadership, governance, and strategic direction of the university.",
        positions: [
          { id: 1, title: "Vice-Chancellor" },
          { id: 2, title: "Chief of Staff" },
          { id: 3, title: "Director: Office of the Vice-Chancellor" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Executive Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Marketing and Communications",
        description: "Promotes university image, branding, and stakeholder communication.",
        positions: [
          { id: 1, title: "Director: Marketing and Communications" },
          { id: 2, title: "Communications Officer" },
          { id: 3, title: "Marketing Officer" },
          { id: 4, title: "Graphic Designer" },
          { id: 5, title: "Photographer/Videographer" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "DVC: Academic",
    type: "Executive",
    description: "Oversees teaching, learning, academic planning, and student academic success.",
    departments: [
      {
        id: 1,
        name: "Academic Planning and Development",
        description: "Curriculum development, academic planning, and programme accreditation.",
        positions: [
          { id: 1, title: "Deputy Vice-Chancellor: Academic" },
          { id: 2, title: "Director: Academic Planning" },
          { id: 3, title: "Curriculum Officer" },
          { id: 4, title: "Programme Accreditation Officer" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Executive Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Teaching and Learning Support",
        description: "Enhances teaching quality, learning technologies, and academic staff development.",
        positions: [
          { id: 1, title: "Director: Teaching and Learning" },
          { id: 2, title: "Instructional Designer" },
          { id: 3, title: "Academic Development Practitioner" },
          { id: 4, title: "E-Learning Specialist" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Executive Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "Registrar’s Office",
    type: "Executive",
    description: "Responsible for academic administration, student records, examinations, and governance processes.",
    departments: [
      {
        id: 1,
        name: "Student Records and Administration",
        description: "Manages student registrations, records, graduations, and certifications.",
        positions: [
          { id: 0, title: "Registrar" },
          { id: 1, title: "Deputy Registrar" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Manager" },
          { id: 4, title: "Senior Administrator" },
          { id: 5, title: "Administrator" },
          { id: 6, title: "Records Officer" },
          { id: 8, title: "Administrative Assistant" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Examinations and Timetabling",
        description: "Coordinates examinations, assessments, and academic timetables.",
        positions: [
          { id: 1, title: "Examinations Manager" },
          { id: 2, title: "Examinations Officer" },
          { id: 3, title: "Timetabling Officer" },
          { id: 8, title: "Administrative Assistant" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Legal Services",
        description: "Ensures institutional legal compliance and governance.",
        positions: [
          { id: 1, title: "University Legal Advisor" },
          { id: 2, title: "Compliance Officer" },
          { id: 3, title: "Administrator" },
          { id: 8, title: "Administrative Assistant" },
          { id: 9, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "DVC: Research, Innovation and Postgraduate Studies",
    type: "Executive",
    description: "Oversees research development, innovation, ethics, and postgraduate education.",
    departments: [
      {
        id: 1,
        name: "Research Development Office",
        description: "Supports research funding, capacity development, and outputs.",
        positions: [
          { id: 1, title: "Deputy Vice-Chancellor: Research, Innovation and Postgraduate Studies" },
          { id: 2, title: "Director: Research Office" },
          { id: 3, title: "Research Development Officer" },
          { id: 4, title: "Research Administrator" },
          { id: 7, title: "Executive Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Postgraduate Studies",
        description: "Manages postgraduate admissions, progression, and supervision support.",
        positions: [
          { id: 1, title: "Director: Postgraduate Studies" },
          { id: 2, title: "Postgraduate Coordinator" },
          { id: 3, title: "Thesis Examination Officer" },
          { id: 4, title: "Administrator" },
          { id: 5, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Innovation, Commercialisation and Technology Transfer",
        description: "Manages intellectual property, innovation initiatives, and industry partnerships.",
        positions: [
          { id: 1, title: "Innovation Manager" },
          { id: 2, title: "Technology Transfer Officer" },
          { id: 3, title: "Industry Liaison Officer" },
          { id: 4, title: "Administrator" },
          { id: 5, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Research Ethics and Integrity",
        description: "Ensures ethical compliance and research integrity.",
        positions: [
          { id: 1, title: "Research Ethics Chair" },
          { id: 2, title: "Research Ethics Officer" },
          { id: 3, title: "Administrator" },
          { id: 4, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "Office of the Chief Financial Officer",
    type: "Executive",
    description: "Manages all financial operations, planning, and reporting.",
    departments: [
      {
        id: 1,
        name: "Finance Department",
        description: "Responsible for budgeting, accounting, and financial reporting.",
        positions: [
          { id: 1, title: "Chief Financial Officer" },
          { id: 2, title: "Director: Finance" },
          { id: 3, title: "Finance Manager" },
          { id: 4, title: "Accountant" },
          { id: 5, title: "Payroll Officer" },
          { id: 7, title: "Executive Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Procurement",
        description: "Manages acquisition of goods and services for the university.",
        positions: [
          { id: 1, title: "Procurement Manager" },
          { id: 2, title: "Supply Chain Officer" },
          { id: 3, title: "Administrator" },
          { id: 4, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "Office of the Chief Operations Officer",
    type: "Executive",
    description: "Oversees operational management, human resources, and facilities.",
    departments: [
      {
        id: 1,
        name: "Human Resources",
        description: "Employee recruitment, development, and welfare management.",
        positions: [
          { id: 1, title: "HR Director" },
          { id: 2, title: "HR Manager" },
          { id: 3, title: "Senior HR Officer" },
          { id: 4, title: "HR Officer" },
          { id: 5, title: "Training Coordinator" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Facilities Management",
        description: "Manages campus buildings, maintenance, and logistics.",
        positions: [
          { id: 1, title: "Facilities Manager" },
          { id: 2, title: "Maintenance Supervisor" },
          { id: 3, title: "Administrator" },
          { id: 4, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Campus Security",
        description: "Ensures safety and security across campus.",
        positions: [
          { id: 5, title: "Executive Director" },
          { id: 1, title: "Security Manager" },
          { id: 6, title: "Investigation Officer" },
          { id: 2, title: "Security Supervisor" },
          { id: 3, title: "Security Officer" },
          { id: 4, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "Office of the Chief Information Officer",
    type: "Executive",
    description: "Responsible for ICT infrastructure, digital services, and cybersecurity.",
    departments: [
      {
        id: 1,
        name: "ICT",
        description: "Manages IT systems, networks, and user support.",
        positions: [
          { id: 1, title: "CIO" },
          { id: 2, title: "Director: ICT Customer Support and Audio Visual" },
          { id: 3, title: "Director: Information Security Service and Governance" },
          { id: 7, title: "Executive Assistant" },
          { id: 4, title: "Bussiness Analyst" },
          { id: 5, title: "Systems Analyst" },
          { id: 6, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Customer Support",
        description: "Oversees cybersecurity, risk management, and data protection.",
        positions: [
          { id: 1, title: "Manager: Customer Support" },
          { id: 2, title: "ICT Support Technician" },
          { id: 5, title: "Service Desk Operator" },
          { id: 3, title: "Administrator" },
          { id: 4, title: "Intern" },
        ],
      },
      {
        id: 5,
        name: "Audio and Visual Support",
        description: "Oversees cybersecurity, risk management, and data protection.",
        positions: [
          { id: 1, title: "Manager: Audio and Visual Support" },
          { id: 2, title: "E-Technologist" },
          { id: 3, title: "Administrator" },
          { id: 4, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Information Security",
        description: "Oversees cybersecurity, risk management, and data protection.",
        positions: [
          { id: 1, title: "Manager: Cybersecurity" },
          { id: 2, title: "Information Security Officer" },
          { id: 3, title: "Risk and Compliance Analyst" },
          { id: 4, title: "Administrator" },
          { id: 5, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Networking Security",
        description: "Oversees cybersecurity, risk management, and data protection.",
        positions: [
          { id: 1, title: "Manager: Networks" },
          { id: 1, title: "Network Engineer" },
          { id: 1, title: "Network Administrator" },
          { id: 3, title: "Administrator" },
          { id: 4, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "Office of the Dean of Student Affairs",
    type: "Executive",
    description: "Manages student welfare, support services, and residence life.",
    departments: [
      {
        id: 1,
        name: "Student Support Services",
        description: "Provides counselling, career guidance, and peer support.",
        positions: [
          { id: 1, title: "Dean of Students" },
          { id: 2, title: "Student Counsellor" },
          { id: 3, title: "Career Development Officer" },
          { id: 4, title: "Peer Mentor" },
          { id: 5, title: "Administrator" },
          { id: 6, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Residences and Accommodation",
        description: "Manages student housing, residence administration, and residential life programs.",
        positions: [
          { id: 1, title: "Residence Warden" },
          { id: 2, title: "Residence Manager" },
          { id: 3, title: "Residence Assistant" },
          { id: 4, title: "Administrator" },
          { id: 5, title: "Intern" },
        ],
      },
    ],
  },

  // 🔹 Academic Faculties
  {
    faculty: "NAS",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Mathematics and Statistics",
        description: "Mathematical theory, applied mathematics, and statistics.",
        positions: [
          { id: 0, title: "Dean" },
          { id: 1, title: "Deputy Dean" },
          { id: 2, title: "Head of Department" },
          { id: 3, title: "Professor" },
          { id: 4, title: "Associate Professor" },
          { id: 5, title: "Senior Lecturer" },
          { id: 6, title: "Lecturer" },
          { id: 7, title: "Researcher" },
          { id: 8, title: "Manager" },
          { id: 9, title: "Senior Manager" },
          { id: 10, title: "Tutor" },
          { id: 11, title: "Administrator" },
          { id: 12, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Computer Science",
        description: "Software engineering, programming, and data science.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Lab Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Teaching Assistant" },
          { id: 9, title: "Administrator" },
          { id: 10, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Physics",
        description: "Matter, energy, and physical sciences.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Laboratory Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Chemistry",
        description: "Chemical reactions, materials, and molecular research.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Research Assistant" },
          { id: 5, title: "Laboratory Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 5,
        name: "Biological Sciences",
        description: "Life sciences, genetics, and environmental biology.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Lab Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 6,
        name: "Geography and Environmental Science",
        description: "Earth systems, GIS, and climate studies.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "GIS Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "EDU",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Educational Studies",
        description: "Education theory, leadership, and management.",
        positions: [
          { id: 0, title: "Dean" },
          { id: 1, title: "Deputy Dean" },
          { id: 2, title: "Head of Department" },
          { id: 3, title: "Professor" },
          { id: 4, title: "Senior Lecturer" },
          { id: 5, title: "Lecturer" },
          { id: 6, title: "Researcher" },
          { id: 7, title: "Manager" },
          { id: 8, title: "Senior Manager" },
          { id: 9, title: "Administrator" },
          { id: 10, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Foundation Phase Teaching",
        description: "Teaching methodologies for early childhood and primary education.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Lecturer" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Tutor" },
          { id: 4, title: "Teaching Assistant" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Language and Social Sciences Education",
        description: "Languages, history, and social science education.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Lecturer" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Researcher" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Tutor" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Mathematics, Science and Technology Education",
        description: "STEM-focused teaching and learning development.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Tutor" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "EMS",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Accounting",
        description: "Financial and management accounting education and research.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Economics",
        description: "Economic theory, econometrics, and applied economics.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Business Management",
        description: "Leadership, entrepreneurship, and organizational management.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Public Administration",
        description: "Governance, public policy, and administrative systems.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Senior Lecturer" },
          { id: 2, title: "Lecturer" },
          { id: 3, title: "Researcher" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "HUM",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Languages and Communication",
        description: "Linguistics, translation, and media communication.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Psychology",
        description: "Human behavior, cognitive science, and counselling.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Psychologist" },
          { id: 5, title: "Researcher" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Sociology and Anthropology",
        description: "Social theory, human culture, and society.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "History and Heritage Studies",
        description: "Historical research, heritage preservation, and cultural studies.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Lecturer" },
          { id: 2, title: "Researcher" },
          { id: 3, title: "Curator" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
    ],
  },
];

/*
[
  {
    "faculty": "NAS",
    "type": "Academic",
    "departments": [
      { "id": 0, "name": "Mathematics and Statistics", "description": "Mathematical theory, applied mathematics, and statistics." },
      { "id": 1, "name": "Computer Science", "description": "Software engineering, programming, and data science." },
      { "id": 2, "name": "Physics", "description": "Matter, energy, and physical sciences." },
      { "id": 3, "name": "Chemistry", "description": "Chemical reactions, materials, and molecular research." },
      { "id": 4, "name": "Biological Sciences", "description": "Life sciences, genetics, and environmental biology." },
      { "id": 5, "name": "Geography and Environmental Science", "description": "Earth systems, GIS, and climate studies." }
    ]
  },
  {
    "faculty": "EDU",
    "type": "Academic",
    "departments": [
      { "id": 6, "name": "Educational Psychology", "description": "Learning behavior and cognitive development." },
      { "id": 7, "name": "Curriculum Studies", "description": "Design and development of educational content." },
      { "id": 8, "name": "Foundation Phase Education", "description": "Teaching at early childhood and primary levels." },
      { "id": 9, "name": "Education Management and Leadership", "description": "School management and educational policy." },
      { "id": 10, "name": "Inclusive Education", "description": "Special needs and learning support." }
    ]
  },
  {
    "faculty": "EMS",
    "type": "Academic",
    "departments": [
      { "id": 11, "name": "Accounting", "description": "Financial reporting, auditing, and taxation." },
      { "id": 12, "name": "Economics", "description": "Microeconomics, macroeconomics, and policy analysis." },
      { "id": 13, "name": "Business Management", "description": "Organisational strategy and operations." },
      { "id": 14, "name": "Marketing", "description": "Consumer behaviour, branding, and communications." },
      { "id": 15, "name": "Public Administration", "description": "Governance, leadership, and service delivery." },
      { "id": 16, "name": "Finance and Banking", "description": "Investment, risk management, and banking." }
    ]
  },
  {
    "faculty": "HUM",
    "type": "Academic",
    "departments": [
      { "id": 17, "name": "Languages and Communication", "description": "Linguistics, literature, and media communication." },
      { "id": 18, "name": "History and Political Studies", "description": "Historical analysis and political systems." },
      { "id": 19, "name": "Philosophy and Ethics", "description": "Logic, ethics, and philosophy." },
      { "id": 20, "name": "Psychology", "description": "Human behaviour, cognition, and emotion." },
      { "id": 21, "name": "Sociology and Anthropology", "description": "Social systems, culture, and human interaction." },
      { "id": 22, "name": "Fine Arts and Design", "description": "Artistic expression, design, and creative studies." }
    ]
  },
  {
    "faculty": "Operations",
    "type": "Support",
    "departments": [
      { "id": 23, "name": "ICT Services", "description": "Manages IT infrastructure, systems, and cybersecurity." },
      { "id": 24, "name": "Human Resources", "description": "Staff recruitment, wellness, and labour relations." },
      { "id": 25, "name": "Finance", "description": "Budgeting, payroll, and financial reporting." },
      { "id": 26, "name": "Registrar’s Office", "description": "Student records, registration, and examinations." },
      { "id": 27, "name": "Library and Information Services", "description": "Academic resources, digital archives, and library systems." },
      { "id": 28, "name": "Marketing and Communications", "description": "Public relations, branding, and media management." },
      { "id": 29, "name": "Legal and Compliance", "description": "Contracts, governance, and institutional compliance." },
      { "id": 30, "name": "Facilities Management", "description": "Campus infrastructure, maintenance, and transport." },
      { "id": 31, "name": "Student Affairs", "description": "Student support, residence life, and counselling." },
      { "id": 32, "name": "Security and Risk Management", "description": "Campus security and risk mitigation." },
      { "id": 33, "name": "Internal Audit", "description": "Internal controls and performance assurance." },
      { "id": 34, "name": "Research and Innovation Office", "description": "Research ethics, grants, and innovation projects." },
      { "id": 35, "name": "Quality Assurance", "description": "Institutional performance and accreditation standards." },
      { "id": 36, "name": "Procurement and Supply Chain", "description": "Purchasing, tenders, and asset management." },
      { "id": 37, "name": "Health Services", "description": "Campus clinic, occupational health, and wellness." },
      { "id": 38, "name": "Alumni Relations", "description": "Engagement with graduates and donors." },
      { "id": 39, "name": "Sports and Recreation", "description": "Athletics, fitness, and student recreation facilities." }
    ]
  }
]
*/

//Latest

/*
 [
  {
    faculty: "NAS",
    type: "Academic",
    departments: [
      { id: 0, name: "Mathematics and Statistics", description: "Mathematical theory, applied mathematics, and statistics." },
      { id: 1, name: "Computer Science", description: "Software engineering, programming, and data science." },
      { id: 2, name: "Physics", description: "Matter, energy, and physical sciences." },
      { id: 3, name: "Chemistry", description: "Chemical reactions, materials, and molecular research." },
      { id: 4, name: "Biological Sciences", description: "Life sciences, genetics, and environmental biology." },
      { id: 5, name: "Geography and Environmental Science", description: "Earth systems, GIS, and climate studies." },
    ],
  },
  {
    faculty: "EDU",
    type: "Academic",
    departments: [
      { id: 6, name: "Educational Psychology", description: "Learning behavior and cognitive development." },
      { id: 7, name: "Curriculum Studies", description: "Design and development of educational content." },
      { id: 8, name: "Foundation Phase Education", description: "Teaching at early childhood and primary levels." },
      { id: 9, name: "Education Management and Leadership", description: "School management and educational policy." },
      { id: 10, name: "Inclusive Education", description: "Special needs and learning support." },
    ],
  },
  {
    faculty: "EMS",
    type: "Academic",
    departments: [
      { id: 11, name: "Accounting", description: "Financial reporting, auditing, and taxation." },
      { id: 12, name: "Economics", description: "Microeconomics, macroeconomics, and policy analysis." },
      { id: 13, name: "Business Management", description: "Organisational strategy and operations." },
      { id: 14, name: "Marketing", description: "Consumer behaviour, branding, and communications." },
      { id: 15, name: "Public Administration", description: "Governance, leadership, and service delivery." },
      { id: 16, name: "Finance and Banking", description: "Investment, risk management, and banking." },
    ],
  },
  {
    faculty: "HUM",
    type: "Academic",
    departments: [
      { id: 17, name: "Languages and Communication", description: "Linguistics, literature, and media communication." },
      { id: 18, name: "History and Political Studies", description: "Historical analysis and political systems." },
      { id: 19, name: "Philosophy and Ethics", description: "Logic, ethics, and philosophy." },
      { id: 20, name: "Psychology", description: "Human behaviour, cognition, and emotion." },
      { id: 21, name: "Sociology and Anthropology", description: "Social systems, culture, and human interaction." },
      { id: 22, name: "Fine Arts and Design", description: "Artistic expression, design, and creative studies." },
    ],
  },
  {
    faculty: "Operations",
    type: "Support",
    departments: [
      { id: 23, name: "ICT Services", description: "Manages IT infrastructure, systems, and cybersecurity." },
      { id: 24, name: "Human Resources", description: "Staff recruitment, wellness, and labour relations." },
      { id: 25, name: "Finance", description: "Budgeting, payroll, and financial reporting." },
      { id: 26, name: "Registrar’s Office", description: "Student records, registration, and examinations." },
      { id: 27, name: "Library and Information Services", description: "Academic resources, digital archives, and library systems." },
      { id: 28, name: "Marketing and Communications", description: "Public relations, branding, and media management." },
      { id: 29, name: "Legal and Compliance", description: "Contracts, governance, and institutional compliance." },
      { id: 30, name: "Facilities Management", description: "Campus infrastructure, maintenance, and transport." },
      { id: 31, name: "Student Affairs", description: "Student support, residence life, and counselling." },
      { id: 32, name: "Security and Risk Management", description: "Campus security and risk mitigation." },
      { id: 33, name: "Internal Audit", description: "Internal controls and performance assurance." },
      { id: 34, name: "Research and Innovation Office", description: "Research ethics, grants, and innovation projects." },
      { id: 35, name: "Quality Assurance", description: "Institutional performance and accreditation standards." },
      { id: 36, name: "Procurement and Supply Chain", description: "Purchasing, tenders, and asset management." },
      { id: 37, name: "Health Services", description: "Campus clinic, occupational health, and wellness." },
      { id: 38, name: "Alumni Relations", description: "Engagement with graduates and donors." },
      { id: 39, name: "Sports and Recreation", description: "Athletics, fitness, and student recreation facilities." },
    ],
  },
];
*/
