export const departmentsList = [
  {
    faculty: "Office of the Vice-Chancellor",
    type: "Executive",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Office of the Vice-Chancellor",
        description: "Strategic leadership and overall university governance.",
        positions: [
          { id: 0, title: "Vice-Chancellor" },
          { id: 1, title: "Deputy Vice-Chancellor: Academic" },
          { id: 2, title: "Deputy Vice-Chancellor: Research and Innovation" },
          { id: 3, title: "Deputy Vice-Chancellor: Institutional Support" },
          { id: 4, title: "Executive Director" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Executive Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Registrar's Office",
        description: "Manages academic administration, examinations, and student records.",
        positions: [
          { id: 0, title: "Registrar" },
          { id: 1, title: "Deputy Registrar" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Manager" },
          { id: 4, title: "Senior Administrator" },
          { id: 5, title: "Administrator" },
          { id: 6, title: "Records Officer" },
          { id: 7, title: "Examinations Officer" },
          { id: 8, title: "Administrative Assistant" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Institutional Planning and Quality Assurance",
        description: "Leads strategic planning, data analytics, and academic quality monitoring.",
        positions: [
          { id: 0, title: "Director: Institutional Planning" },
          { id: 1, title: "Director: Quality Assurance" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Manager" },
          { id: 4, title: "Quality Assurance Officer" },
          { id: 5, title: "Research Analyst" },
          { id: 6, title: "Data Administrator" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "NAS",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Mathematics and Statistics",
        description: "Mathematical theory, applied mathematics, and statistics.",
        positions: [
          { id: 0, title: "Dean" },
          { id: 1, title: "Deputy Dean" },
          { id: 2, title: "Head of Department" },
          { id: 3, title: "Professor" },
          { id: 4, title: "Associate Professor" },
          { id: 5, title: "Senior Lecturer" },
          { id: 6, title: "Lecturer" },
          { id: 7, title: "Researcher" },
          { id: 8, title: "Manager" },
          { id: 9, title: "Senior Manager" },
          { id: 10, title: "Tutor" },
          { id: 11, title: "Administrator" },
          { id: 12, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Computer Science",
        description: "Software engineering, programming, and data science.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Lab Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Teaching Assistant" },
          { id: 9, title: "Administrator" },
          { id: 10, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Physics",
        description: "Matter, energy, and physical sciences.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Laboratory Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Chemistry",
        description: "Chemical reactions, materials, and molecular research.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Research Assistant" },
          { id: 5, title: "Laboratory Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 5,
        name: "Biological Sciences",
        description: "Life sciences, genetics, and environmental biology.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Lab Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 6,
        name: "Geography and Environmental Science",
        description: "Earth systems, GIS, and climate studies.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "GIS Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "EDU",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Educational Studies",
        description: "Education theory, leadership, and management.",
        positions: [
          { id: 0, title: "Dean" },
          { id: 1, title: "Deputy Dean" },
          { id: 2, title: "Head of Department" },
          { id: 3, title: "Professor" },
          { id: 4, title: "Senior Lecturer" },
          { id: 5, title: "Lecturer" },
          { id: 6, title: "Researcher" },
          { id: 7, title: "Manager" },
          { id: 8, title: "Senior Manager" },
          { id: 9, title: "Administrator" },
          { id: 10, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Foundation Phase Teaching",
        description: "Teaching methodologies for early childhood and primary education.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Lecturer" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Tutor" },
          { id: 4, title: "Teaching Assistant" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Language and Social Sciences Education",
        description: "Languages, history, and social science education.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Lecturer" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Researcher" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Tutor" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Mathematics, Science and Technology Education",
        description: "STEM-focused teaching and learning development.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Tutor" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "EMS",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Accounting",
        description: "Financial and management accounting education and research.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Economics",
        description: "Economic theory, econometrics, and applied economics.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Business Management",
        description: "Leadership, entrepreneurship, and organizational management.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Public Administration",
        description: "Governance, public policy, and administrative systems.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Senior Lecturer" },
          { id: 2, title: "Lecturer" },
          { id: 3, title: "Researcher" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "HUM",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Languages and Communication",
        description: "Linguistics, translation, and media communication.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Psychology",
        description: "Human behavior, cognitive science, and counselling.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Psychologist" },
          { id: 5, title: "Researcher" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Sociology and Anthropology",
        description: "Social theory, human culture, and society.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "History and Heritage Studies",
        description: "Historical research, heritage preservation, and cultural studies.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Lecturer" },
          { id: 2, title: "Researcher" },
          { id: 3, title: "Curator" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "ICT",
    type: "Administrative",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Information and Communication Technology",
        description: "Digital infrastructure, systems support, and information management.",
        positions: [
          { id: 0, title: "Chief Information Officer" },
          { id: 1, title: "Director: ICT Services" },
          { id: 2, title: "Senior Manager: Infrastructure" },
          { id: 3, title: "ICT Manager" },
          { id: 4, title: "Network Administrator" },
          { id: 5, title: "Systems Analyst" },
          { id: 6, title: "Database Administrator" },
          { id: 7, title: "ICT Technician" },
          { id: 8, title: "Support Officer" },
          { id: 9, title: "Administrator" },
          { id: 10, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "Finance",
    type: "Administrative",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Finance Department",
        description: "Manages university finances, budgeting, and reporting.",
        positions: [
          { id: 0, title: "Chief Financial Officer" },
          { id: 1, title: "Director: Finance" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Manager" },
          { id: 4, title: "Senior Finance Officer" },
          { id: 5, title: "Accountant" },
          { id: 6, title: "Procurement Officer" },
          { id: 7, title: "Payroll Officer" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "Human Resources",
    type: "Administrative",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Human Resources Department",
        description: "Employee recruitment, training, and welfare management.",
        positions: [
          { id: 0, title: "Executive Director: Human Resources" },
          { id: 1, title: "Director: HR" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Manager" },
          { id: 4, title: "Senior HR Officer" },
          { id: 5, title: "HR Officer" },
          { id: 6, title: "Training Coordinator" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "Library",
    type: "Administrative",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Library and Information Services",
        description: "Manages library resources and academic information access.",
        positions: [
          { id: 0, title: "Director: Library Services" },
          { id: 1, title: "Senior Librarian" },
          { id: 2, title: "Librarian" },
          { id: 3, title: "Library Assistant" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Cataloguer" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "Marketing and Communications",
    type: "Administrative",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Marketing and Communications",
        description: "Promotes university image, branding, and stakeholder communication.",
        positions: [
          { id: 0, title: "Director: Marketing and Communications" },
          { id: 1, title: "Senior Manager" },
          { id: 2, title: "Manager" },
          { id: 3, title: "Communications Officer" },
          { id: 4, title: "Marketing Officer" },
          { id: 5, title: "Graphic Designer" },
          { id: 6, title: "Photographer/Videographer" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "Student Affairs",
    type: "Administrative",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Student Support Services",
        description: "Supports student welfare, engagement, and development.",
        positions: [
          { id: 1, title: "Director: Student Affairs" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Manager" },
          { id: 4, title: "Student Counsellor" },
          { id: 5, title: "Career Development Officer" },
          { id: 6, title: "Peer Mentor" },
          { id: 7, title: "Student Affairs Officer" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Residences and Accommodation",
        description: "Manages student housing and residential life.",
        positions: [
          { id: 1, title: "Residence Warden" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Residence Manager" },
          { id: 4, title: "Residence Assistant" },
          { id: 5, title: "Administrator" },
          { id: 6, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "Legal and Compliance",
    type: "Administrative",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Legal and Compliance Services",
        description: "Ensures institutional legal compliance and governance.",
        positions: [
          { id: 1, title: "Director: Legal and Compliance" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Manager" },
          { id: 4, title: "Legal Advisor" },
          { id: 5, title: "Compliance Officer" },
          { id: 6, title: "Internal Auditor" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
    ],
  },
];

/*export const departmentEntitiesList = [
  {
    faculty: "Office of the Vice-Chancellor",
    type: "Executive",
    description: "Central executive authority responsible for strategic leadership and institutional oversight.",
    departments: [
      {
        id: 1,
        name: "Office of the Vice-Chancellor",
        description: "Overall leadership, governance, and strategic direction of the university.",
        positions: [
          { id: 1, title: "Vice-Chancellor" },
          { id: 2, title: "Chief of Staff" },
          { id: 3, title: "Director: Office of the Vice-Chancellor" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Executive Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Marketing and Communications",
        description: "Promotes university image, branding, and stakeholder communication.",
        positions: [
          { id: 1, title: "Director: Marketing and Communications" },
          { id: 2, title: "Communications Officer" },
          { id: 3, title: "Marketing Officer" },
          { id: 4, title: "Graphic Designer" },
          { id: 5, title: "Photographer/Videographer" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "DVC: Academic",
    type: "Executive",
    description: "Oversees teaching, learning, academic planning, and student academic success.",
    departments: [
      {
        id: 1,
        name: "Academic Planning and Development",
        description: "Curriculum development, academic planning, and programme accreditation.",
        positions: [
          { id: 1, title: "Deputy Vice-Chancellor: Academic" },
          { id: 2, title: "Director: Academic Planning" },
          { id: 3, title: "Curriculum Officer" },
          { id: 4, title: "Programme Accreditation Officer" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Executive Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Teaching and Learning Support",
        description: "Enhances teaching quality, learning technologies, and academic staff development.",
        positions: [
          { id: 1, title: "Director: Teaching and Learning" },
          { id: 2, title: "Instructional Designer" },
          { id: 3, title: "Academic Development Practitioner" },
          { id: 4, title: "E-Learning Specialist" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Executive Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "Registrar’s Office",
    type: "Executive",
    description: "Responsible for academic administration, student records, examinations, and governance processes.",
    departments: [
      {
        id: 1,
        name: "Student Records and Administration",
        description: "Manages student registrations, records, graduations, and certifications.",
        positions: [
          { id: 0, title: "Registrar" },
          { id: 1, title: "Deputy Registrar" },
          { id: 2, title: "Senior Manager" },
          { id: 3, title: "Manager" },
          { id: 4, title: "Senior Administrator" },
          { id: 5, title: "Administrator" },
          { id: 6, title: "Records Officer" },
          { id: 8, title: "Administrative Assistant" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Examinations and Timetabling",
        description: "Coordinates examinations, assessments, and academic timetables.",
        positions: [
          { id: 1, title: "Examinations Manager" },
          { id: 2, title: "Examinations Officer" },
          { id: 3, title: "Timetabling Officer" },
          { id: 8, title: "Administrative Assistant" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Legal Services",
        description: "Ensures institutional legal compliance and governance.",
        positions: [
          { id: 1, title: "University Legal Advisor" },
          { id: 2, title: "Compliance Officer" },
          { id: 3, title: "Administrator" },
          { id: 8, title: "Administrative Assistant" },
          { id: 9, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "DVC: Research, Innovation and Postgraduate Studies",
    type: "Executive",
    description: "Oversees research development, innovation, ethics, and postgraduate education.",
    departments: [
      {
        id: 1,
        name: "Research Development Office",
        description: "Supports research funding, capacity development, and outputs.",
        positions: [
          { id: 1, title: "Deputy Vice-Chancellor: Research, Innovation and Postgraduate Studies" },
          { id: 2, title: "Director: Research Office" },
          { id: 3, title: "Research Development Officer" },
          { id: 4, title: "Research Administrator" },
          { id: 7, title: "Executive Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Postgraduate Studies",
        description: "Manages postgraduate admissions, progression, and supervision support.",
        positions: [
          { id: 1, title: "Director: Postgraduate Studies" },
          { id: 2, title: "Postgraduate Coordinator" },
          { id: 3, title: "Thesis Examination Officer" },
          { id: 4, title: "Administrator" },
          { id: 5, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Innovation, Commercialisation and Technology Transfer",
        description: "Manages intellectual property, innovation initiatives, and industry partnerships.",
        positions: [
          { id: 1, title: "Innovation Manager" },
          { id: 2, title: "Technology Transfer Officer" },
          { id: 3, title: "Industry Liaison Officer" },
          { id: 4, title: "Administrator" },
          { id: 5, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Research Ethics and Integrity",
        description: "Ensures ethical compliance and research integrity.",
        positions: [
          { id: 1, title: "Research Ethics Chair" },
          { id: 2, title: "Research Ethics Officer" },
          { id: 3, title: "Administrator" },
          { id: 4, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "Office of the Chief Financial Officer",
    type: "Executive",
    description: "Manages all financial operations, planning, and reporting.",
    departments: [
      {
        id: 1,
        name: "Finance Department",
        description: "Responsible for budgeting, accounting, and financial reporting.",
        positions: [
          { id: 1, title: "Chief Financial Officer" },
          { id: 2, title: "Director: Finance" },
          { id: 3, title: "Finance Manager" },
          { id: 4, title: "Accountant" },
          { id: 5, title: "Payroll Officer" },
          { id: 7, title: "Executive Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Procurement",
        description: "Manages acquisition of goods and services for the university.",
        positions: [
          { id: 1, title: "Procurement Manager" },
          { id: 2, title: "Supply Chain Officer" },
          { id: 3, title: "Administrator" },
          { id: 4, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "Office of the Chief Operations Officer",
    type: "Executive",
    description: "Oversees operational management, human resources, and facilities.",
    departments: [
      {
        id: 1,
        name: "Human Resources",
        description: "Employee recruitment, development, and welfare management.",
        positions: [
          { id: 1, title: "HR Director" },
          { id: 2, title: "HR Manager" },
          { id: 3, title: "Senior HR Officer" },
          { id: 4, title: "HR Officer" },
          { id: 5, title: "Training Coordinator" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Facilities Management",
        description: "Manages campus buildings, maintenance, and logistics.",
        positions: [
          { id: 1, title: "Facilities Manager" },
          { id: 2, title: "Maintenance Supervisor" },
          { id: 3, title: "Administrator" },
          { id: 4, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Campus Security",
        description: "Ensures safety and security across campus.",
        positions: [
          { id: 5, title: "Executive Director" },
          { id: 1, title: "Security Manager" },
          { id: 6, title: "Investigation Officer" },
          { id: 2, title: "Security Supervisor" },
          { id: 3, title: "Security Officer" },
          { id: 4, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "Office of the Chief Information Officer",
    type: "Executive",
    description: "Responsible for ICT infrastructure, digital services, and cybersecurity.",
    departments: [
      {
        id: 1,
        name: "ICT",
        description: "Manages IT systems, networks, and user support.",
        positions: [
          { id: 1, title: "CIO" },
          { id: 2, title: "Director: ICT Customer Support and Audio Visual" },
          { id: 3, title: "Director: Information Security Service and Governance" },
          { id: 7, title: "Executive Assistant" },
          { id: 4, title: "Bussiness Analyst" },
          { id: 5, title: "Systems Analyst" },
          { id: 6, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Customer Support",
        description: "Oversees cybersecurity, risk management, and data protection.",
        positions: [
          { id: 1, title: "Manager: Customer Support" },
          { id: 2, title: "ICT Support Technician" },
          { id: 5, title: "Service Desk Operator" },
          { id: 3, title: "Administrator" },
          { id: 4, title: "Intern" },
        ],
      },
      {
        id: 5,
        name: "Audio and Visual Support",
        description: "Oversees cybersecurity, risk management, and data protection.",
        positions: [
          { id: 1, title: "Manager: Audio and Visual Support" },
          { id: 2, title: "E-Technologist" },
          { id: 3, title: "Administrator" },
          { id: 4, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Information Security",
        description: "Oversees cybersecurity, risk management, and data protection.",
        positions: [
          { id: 1, title: "Manager: Cybersecurity" },
          { id: 2, title: "Information Security Officer" },
          { id: 3, title: "Risk and Compliance Analyst" },
          { id: 4, title: "Administrator" },
          { id: 5, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Networking Security",
        description: "Oversees cybersecurity, risk management, and data protection.",
        positions: [
          { id: 1, title: "Manager: Networks" },
          { id: 1, title: "Network Engineer" },
          { id: 1, title: "Network Administrator" },
          { id: 3, title: "Administrator" },
          { id: 4, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "Office of the Dean of Student Affairs",
    type: "Executive",
    description: "Manages student welfare, support services, and residence life.",
    departments: [
      {
        id: 1,
        name: "Student Support Services",
        description: "Provides counselling, career guidance, and peer support.",
        positions: [
          { id: 1, title: "Dean of Students" },
          { id: 2, title: "Student Counsellor" },
          { id: 3, title: "Career Development Officer" },
          { id: 4, title: "Peer Mentor" },
          { id: 5, title: "Administrator" },
          { id: 6, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Residences and Accommodation",
        description: "Manages student housing, residence administration, and residential life programs.",
        positions: [
          { id: 1, title: "Residence Warden" },
          { id: 2, title: "Residence Manager" },
          { id: 3, title: "Residence Assistant" },
          { id: 4, title: "Administrator" },
          { id: 5, title: "Intern" },
        ],
      },
    ],
  },

  // 🔹 Academic Faculties
  {
    faculty: "NAS",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Mathematics and Statistics",
        description: "Mathematical theory, applied mathematics, and statistics.",
        positions: [
          { id: 0, title: "Dean" },
          { id: 1, title: "Deputy Dean" },
          { id: 2, title: "Head of Department" },
          { id: 3, title: "Professor" },
          { id: 4, title: "Associate Professor" },
          { id: 5, title: "Senior Lecturer" },
          { id: 6, title: "Lecturer" },
          { id: 7, title: "Researcher" },
          { id: 8, title: "Manager" },
          { id: 9, title: "Senior Manager" },
          { id: 10, title: "Tutor" },
          { id: 11, title: "Administrator" },
          { id: 12, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Computer Science",
        description: "Software engineering, programming, and data science.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Lab Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Teaching Assistant" },
          { id: 9, title: "Administrator" },
          { id: 10, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Physics",
        description: "Matter, energy, and physical sciences.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Laboratory Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Chemistry",
        description: "Chemical reactions, materials, and molecular research.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Research Assistant" },
          { id: 5, title: "Laboratory Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 5,
        name: "Biological Sciences",
        description: "Life sciences, genetics, and environmental biology.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Lab Assistant" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 6,
        name: "Geography and Environmental Science",
        description: "Earth systems, GIS, and climate studies.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "GIS Technician" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
    ],
  },

  {
    faculty: "EDU",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Educational Studies",
        description: "Education theory, leadership, and management.",
        positions: [
          { id: 0, title: "Dean" },
          { id: 1, title: "Deputy Dean" },
          { id: 2, title: "Head of Department" },
          { id: 3, title: "Professor" },
          { id: 4, title: "Senior Lecturer" },
          { id: 5, title: "Lecturer" },
          { id: 6, title: "Researcher" },
          { id: 7, title: "Manager" },
          { id: 8, title: "Senior Manager" },
          { id: 9, title: "Administrator" },
          { id: 10, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Foundation Phase Teaching",
        description: "Teaching methodologies for early childhood and primary education.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Lecturer" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Tutor" },
          { id: 4, title: "Teaching Assistant" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Language and Social Sciences Education",
        description: "Languages, history, and social science education.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Lecturer" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Researcher" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Tutor" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Mathematics, Science and Technology Education",
        description: "STEM-focused teaching and learning development.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Tutor" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "EMS",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Accounting",
        description: "Financial and management accounting education and research.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Economics",
        description: "Economic theory, econometrics, and applied economics.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Business Management",
        description: "Leadership, entrepreneurship, and organizational management.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "Public Administration",
        description: "Governance, public policy, and administrative systems.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Senior Lecturer" },
          { id: 2, title: "Lecturer" },
          { id: 3, title: "Researcher" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "HUM",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "Languages and Communication",
        description: "Linguistics, translation, and media communication.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "Psychology",
        description: "Human behavior, cognitive science, and counselling.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Psychologist" },
          { id: 5, title: "Researcher" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Senior Manager" },
          { id: 8, title: "Administrator" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "Sociology and Anthropology",
        description: "Social theory, human culture, and society.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Professor" },
          { id: 2, title: "Senior Lecturer" },
          { id: 3, title: "Lecturer" },
          { id: 4, title: "Researcher" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Senior Manager" },
          { id: 7, title: "Administrator" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "History and Heritage Studies",
        description: "Historical research, heritage preservation, and cultural studies.",
        positions: [
          { id: 0, title: "Head of Department" },
          { id: 1, title: "Lecturer" },
          { id: 2, title: "Researcher" },
          { id: 3, title: "Curator" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Senior Manager" },
          { id: 6, title: "Administrator" },
          { id: 7, title: "Intern" },
        ],
      },
    ],
  },
];*/

export const departmentEntitiesList = [
  {
    faculty: "VICE CHANCELLOR AND PRINCIPAL",
    type: "Executive",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "DVC: ACADEMIC",
        description: "",
        positions: [
          { id: 0, title: "PERSONAL ASSISTANT: DVC T & L" },
          { id: 1, title: "DVC: TEACHING AND LEARNING" },
          { id: 2, title: "PERSONAL ASSISTANT" },
          { id: 3, title: "Manager" },
          { id: 4, title: "Director" },
          { id: 5, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "CHIEF OPERATING OFFICER",
        description: "",
        positions: [
          { id: 0, title: "GENERAL ASSISTANT: PROPERTY MANAGEMENT" },
          { id: 1, title: "DIRECTOR:PROPERTY MANAGEMENT" },
          { id: 2, title: "CHIEF OPERATING OFFICER" },
          { id: 3, title: "MAINTENANCE ASSISTANT" },
          { id: 4, title: "INFRASTRUCTURE PROJECT MANAGER" },
          { id: 5, title: "SENIOR MANAGER:PROPERTY MANAGEMENT" },
          { id: 6, title: "OFFICER:PROPERTY MANAGEMENT" },
          { id: 7, title: "PERSONAL ASSISTANT" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "VICE CHANCELLOR",
        description: "",
        positions: [
          { id: 1, title: "CENTRE MANAGER CFERI UPINGTON" },
          { id: 2, title: "MAKER SPACE TECHNICAL ASSISTANT" },
          { id: 3, title: "DVC:RESEARCH" },
          { id: 4, title: "CfERI RECEPTIONIST" },
          { id: 5, title: "DIRECTOR FOR RENEWABLE & SUST ENERGY" },
          { id: 6, title: "BUSINESS DEVELOPMENT OFFICER" },
          { id: 7, title: "PERSONAL ASSISTANT TO THE VC" },
          { id: 8, title: "VICE CHANCELLOR & PRINCIPAL" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "STUDENT AFFAIRS",
        description: "",
        positions: [
          { id: 0, title: "COACH:CRICKET" },
          { id: 1, title: "MENS FOOTBALL ASSISTANT COACH" },
          { id: 2, title: "COACH:FOOTBALL" },
          { id: 3, title: "SENIOR MANAGER: SPORT" },
          { id: 4, title: "SPORTS DOCTOR" },
          { id: 5, title: "LINE OUT COACH" },
          { id: 6, title: "GYM MANAGER AND ATHLETICS COACH" },
          { id: 7, title: "COACH:CHEERLEADING" },
          { id: 8, title: "COACH:DANCE &AEROBICS" },
          { id: 9, title: "RUGBY ASSISTANT COACH" },
          { id: 10, title: "STRENGTH AND CONDITIONING COACH" },
          { id: 11, title: "ADMINISTRATOR" },
          { id: 12, title: "COACH:BASKETBALL" },
          { id: 13, title: "SDG Administrator" },
          { id: 14, title: "WOMANS FOOTBALL ASSISTANT COACH" },
          { id: 15, title: "FOOTBALL ASSISTANT COACH MALE B TEAM" },
          { id: 16, title: "NETBALL HEAD COACH" },
          { id: 17, title: "SOCIAL WORKER" },
          { id: 18, title: "DRAMA TRAINER" },
          { id: 19, title: "RUGBY TEAM MANAGER MALES" },
          { id: 20, title: "SENIOR ADMINISTRATOR: STUDENT AFFAIRS" },
          { id: 21, title: "STUDENT COUNSELLOR" },
          { id: 22, title: "GOALKEEPER COACH" },
          { id: 23, title: "OFFICER:CAREER SERVICES" },
          { id: 24, title: "BIOKINETICIST" },
          { id: 25, title: "CHOIR CONDUCTOR" },
          { id: 26, title: "EXECUTIVE PERSONAL ASSISTANT" },
          { id: 27, title: "OFFICER: STUDENT DEVELOPMENT" },
          { id: 28, title: "COACH:RUGBY" },
          { id: 29, title: "PHYSIOTHERAPIST" },
          { id: 30, title: "COACH:VOLLEBALL" },
          { id: 31, title: "COACH:VOLLEYBALL" },
          { id: 32, title: "COACH: RUGBY" },
          { id: 33, title: "COACH:RUGBY FORWARD" },
          { id: 34, title: "SENIOR OFFICER: PRIMARY HEALTH" },
          { id: 35, title: "Director" },
          { id: 36, title: "Intern" },
        ],
      },
      {
        id: 5,
        name: "INFORMATION TECHNOLOGY",
        description: "",
        positions: [
          { id: 0, title: "MANAGER: CUSTOMER SUPPORT" },
          { id: 1, title: "BUSINESS ANALYST" },
          { id: 2, title: "SERVICE DESK OPERATOR" },
          { id: 3, title: "MANAGER: NETWORK INFRASTRUCTURE" },
          { id: 4, title: "IT SUPPORT TECHNICIAN" },
          { id: 5, title: "Officer: Administration" },
          { id: 6, title: "DEPUTY DIRECTOR: ICT GOVERNANCE & CYBER" },
          { id: 7, title: "ELEARNING TECHNOLOGIST" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 6,
        name: "REGISTRARS OFFICE",
        description: "",
        positions: [
          { id: 0, title: "OFFICER: LEGAL SERVICES" },
          { id: 1, title: "OFFICER: SECRETARIAT" },
          { id: 2, title: "TPP COORDINATOR" },
          { id: 3, title: "OFFICER: ADMINISTRATION" },
          { id: 4, title: "ADMINISTRATOR:APPLICATIONS AND ADMISSI" },
          { id: 5, title: "OFFICER:LEGAL SERVICES" },
          { id: 6, title: "UNIVERSITY REGISTRAR" },
          { id: 7, title: "OFFICER:SYSTEMS SUPPORT AND HEMIS" },
          { id: 8, title: "SENIOR MANAGER: SYSTEM SUPPORT" },
          { id: 9, title: "SENIOR ADMINISTRATOR: SECRETRIAT" },
          { id: 10, title: "OFFICER: SYSTEMS SUPPORT ITS" },
          { id: 11, title: "ADMINISTRATOR: OFFICE OF THE VC" },
          { id: 12, title: "SENIOR OFFICER:OFFICE OF THE REGISTRAR" },
          { id: 13, title: "ADMINISTRATIVE OFFICER: REGISTR. & EXAMS" },
          { id: 14, title: "DIRECTOR ACADEMIC ADMINISTRATION" },
          { id: 15, title: "SENIOR OFFICER: SECRETARIAT" },
          { id: 16, title: "ADMINISTRATOR: APPLICATIONS & ADMISSIONS" },
          { id: 17, title: "MANAGER: ACADEMIC ADMINISTRATION" },
          { id: 18, title: "MANAGER: SECRETARIAT" },
          { id: 19, title: "OFFICER: ADMINISTRATION (LEGAL OFFICE)" },
          { id: 20, title: "Intern" },
        ],
      },
      {
        id: 7,
        name: "MARKETING & COMMUNICATIONS",
        description: "",
        positions: [
          { id: 0, title: "OFFICER: MARKETING AND COMMUNICATIONS" },
          { id: 1, title: "OFFICER ADVANCEMENT" },
          { id: 2, title: "UNIFIED CALL DESK OPERATOR" },
          { id: 3, title: "OFFICER: ALUMNI & EVENTS" },
          { id: 4, title: "SENIOR OFFICER:COMM & MARKETING" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Director" },
          { id: 7, title: "Intern" },
        ],
      },
      {
        id: 8,
        name: "RESIDENCE",
        description: "",
        positions: [
          { id: 0, title: "ADMINISTRATOR:RESIDENCE" },
          { id: 1, title: "CLUSTER COORDINATOR" },
          { id: 2, title: "ADMINISTRATOR RESIDENCES" },
          { id: 3, title: "ADMINISTRATOR: STUDENT ACCOMMODATION" },
          { id: 4, title: "Manager" },
          { id: 5, title: "Director" },
          { id: 6, title: "Intern" },
        ],
      },
      {
        id: 9,
        name: "INTERNAL AUDIT",
        description: "",
        positions: [
          { id: 0, title: "MANAGER: INTERNAL AUDIT" },
          { id: 1, title: "OFFICER INTERNAL AUDIT" },
          { id: 2, title: "DIRECTOR: INTERNAL AUDIT" },
          { id: 3, title: "OFFICER: INTERNAL AUDIT" },
          { id: 4, title: "MANAGER: RISK MANAGEMENT" },
        ],
      },
    ],
  },
  {
    faculty: "FACULTY OF ECONOMIC & MAN SC",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "MANAGEMENT SCIENCES",
        description: "",
        positions: [
          { id: 0, title: "SENIOR LECTURER:PUBLIC FINANCE" },
          { id: 1, title: "SENIOR LECTURER: RETAIL MANAGEMENT" },
          { id: 2, title: "LECTURER: WORK INTEGRATED LEARNING" },
          { id: 3, title: "LECTURER: ENTREPRENEURSHIP" },
          { id: 4, title: "LECTURER: PUBLIC BUSINESS MANAGEMENT" },
          { id: 5, title: "SENIOR LECTURER" },
          { id: 6, title: "ASSOCIATE PROFESSOR:MANAGEMENT" },
          { id: 7, title: "LECTURER: INDUSTRIAL RELAT. & LABOUR LAW" },
          { id: 8, title: "JUNIOR LECTURER: COMMUNICATION" },
          { id: 9, title: "LECTURER: ACCOUNTING" },
          { id: 10, title: "LECTURER: BUSINESS MAN & ADMIN" },
          { id: 11, title: "LECTURER: BUSINESS MANAGEMENT" },
          { id: 12, title: "LECTURER: BUSINESS MANAGEMENT/ADMIN" },
          { id: 13, title: "LECTURER: ENTREPRENEURSHIP (nGAP)" },
          { id: 14, title: "SENIOR LECTURER: LOGISTICS & OPERATIONS" },
          { id: 15, title: "SENIOR LECTURER:PUBLIC MANAGEMENT" },
          { id: 16, title: "Manager" },
          { id: 17, title: "Director" },
          { id: 18, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "EMS ADMIN",
        description: "",
        positions: [
          { id: 0, title: "FACULTY ADMINISTRATOR" },
          { id: 1, title: "OFFICER:ECONOMIC ACTIVATION" },
          { id: 2, title: "SENIOR FACULTY ADMINISTRATOR" },
          { id: 3, title: "DEAN:ECOMOMIC AND MANAGEMENT SCIENCES" },
          { id: 4, title: "OFFICER: ADMINISTRATION" },
          { id: 5, title: "FACULTY MANAGER: ACADEMIC ADMINISTRATION" },
          { id: 6, title: "PERSONAL ASSISTANT:DEAN EMS" },
          { id: 7, title: "Director" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "ACCOUNTING & ECONOMICS",
        description: "",
        positions: [
          { id: 0, title: "SENIOR LECTURER: QUANT TECHNIQUES IN ECO" },
          { id: 1, title: "PROFESSOR: ECONOMICS" },
          { id: 2, title: "LECTURER: ACCOUNTING & FINANCIAL MAN" },
          { id: 3, title: "LECTURER:ACCOUNTING" },
          { id: 4, title: "LECTURER: ECONOMICS" },
          { id: 5, title: "ASSOCIATE PROFESSOR:ACCOUNTING AND FIN" },
          { id: 6, title: "SENIOR LECTURER: ECONOMICS" },
          { id: 7, title: "LECTURER: ACCOUNTING" },
          { id: 8, title: "LECTURER: ACCOUNTING AND FIN MANAGEMENT" },
          { id: 9, title: "LECTURER: FINANCIAL MANAGEMENT" },
          { id: 10, title: "Manager" },
          { id: 11, title: "Director" },
          { id: 12, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "OFFICE OF THE COO",
    type: "Executive",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "SECURITY",
        description: "",
        positions: [
          { id: 0, title: "SECURITY OFFICER" },
          { id: 1, title: "ADMINISTRATOR: INVESTIGATIONS" },
          { id: 2, title: "ADMINISTRATIVE ASSISTANT: SECURITY OPS" },
          { id: 3, title: "SENIOR ADMINISTRATOR:SECURITY SYSTEMS" },
          { id: 4, title: "OFFICER: SECTIONS" },
          { id: 5, title: "MANAGER: CAMPUS SECURITY" },
          { id: 6, title: "ASSISTANT: SECTIONS" },
          { id: 7, title: "OFFICER: INVESTIGATIONS" },
          { id: 8, title: "CONTROL ROOM OPERATOR" },
          { id: 9, title: "SENIOR MANAGER: CAMPUS SECURITY" },
          { id: 10, title: "LOCKSMITH" },
          { id: 11, title: "Director" },
          { id: 12, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "FACILITIES",
        description: "",
        positions: [
          { id: 0, title: "CLEANER" },
          { id: 1, title: "GENERAL ASSISTANT" },
          { id: 2, title: "STOREMAN: CLEANING" },
          { id: 3, title: "SENIOR MANAGER:FACILITIES" },
          { id: 4, title: "GENERAL ASSISTANT: TRANSPORT" },
          { id: 5, title: "SUPERVISOR:CLEANING" },
          { id: 6, title: "FOREMAN: MAINTENANCE" },
          { id: 7, title: "GENERAL ASSISTANT: LANDSCAPING" },
          { id: 8, title: "GENERAL ASSISTANT: PROPERTY MANAGEMENT" },
          { id: 9, title: "GENERAL ASSISTANT: WASTE MANAGEMENT" },
          { id: 10, title: "DRIVER" },
          { id: 11, title: "OFFICER: SAFETY AND HEALTH" },
          { id: 12, title: "DIRECTOR: FACILITIES & SERVICES" },
          { id: 13, title: "OFFICER: FACILITIES AND SERVICES" },
          { id: 14, title: "ADMINISTRATOR:HELPDESK" },
          { id: 15, title: "GENERAL  ASSISTANT" },
          { id: 16, title: "SENIOR OFFICER: OHS & E" },
          { id: 17, title: "ARTISAN" },
          { id: 18, title: "OFFICER: SAFETY" },
          { id: 19, title: "SENIOR OFFICER: LANDSCAPING" },
          { id: 20, title: "STOREMAN: MAINTENANCE" },
          { id: 21, title: "SUPERVISOR: CLEANING" },
          { id: 22, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "CLEANING SERVICES",
        description: "",
        positions: [
          { id: 0, title: "CLEANER" },
          { id: 1, title: "SUPERVISOR: CLEANING" },
          { id: 2, title: "CLEANING SUPERVISOR" },
          { id: 3, title: "ADMIN OFFICER: CLEANING & HYGIENE SERV." },
          { id: 4, title: "FOOD SERVICE ASSISTANT" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Director" },
          { id: 7, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "HUMAN RESOURCES",
        description: "",
        positions: [
          { id: 0, title: "OFFICER: HR" },
          { id: 1, title: "MANAGER:HR OPERATIONS" },
          { id: 2, title: "SENIOR OFFICER: HR" },
          { id: 3, title: "SENIOR ADMINISTRATOR: HR" },
          { id: 4, title: "MANAGER: HR DEVELOPMENT" },
          { id: 5, title: "MANAGER:EMPLOYMENT RELATIONS" },
          { id: 6, title: "DIRECTOR: HUMAN RESOURCES" },
          { id: 7, title: "INTERN" },
          { id: 8, title: "OFFICER: EMPLOYMENT RELATIONS AND WELLNE" },
          { id: 9, title: "OFFICER: REM AND BENFITS" },
          { id: 10, title: "SENIOR OFFICER: EMPLOYMENT RELATIONS" },
          { id: 11, title: "ADMINISTRATOR:HR OPERATIONS" },
          { id: 12, title: "ADMINISTRATOR:LEARNING AND DEVELOPMENT" },
          { id: 13, title: "OFFICER:HR OPERATIONS" },
          { id: 14, title: "SENIOR ADMINISTRATOR:HR" },
          { id: 15, title: "TRAINING COORDINATOR" },
        ],
      },
    ],
  },
  {
    faculty: "FACULTY OF NATURAL&APPLIED SC",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "PHYSICAL & EARTH SCIENCES",
        description: "",
        positions: [
          { id: 0, title: "ASSOCIATE PROFESSOR" },
          { id: 1, title: "SENIOR LECTURER:PHYSICS" },
          { id: 2, title: "LECTURER:PHYSICS" },
          { id: 3, title: "SENIOR LECTURER: PHYSICAL CHEMISTRY" },
          { id: 4, title: "LECTURER: ORGANIC CHEMISTRY" },
          { id: 5, title: "LABORATORY TECHNICIAN: CHEMISTRY" },
          { id: 6, title: "LABORATORY TECHNICIAN: GEOGRAPHY" },
          { id: 7, title: "LECTURER: INORGANIC CHEMISTRY" },
          { id: 8, title: "LECTURER: PHYSICS" },
          { id: 9, title: "LECTURER: ANALYTICAL CHEMISTRY" },
          { id: 10, title: "ASSOCIATE PROFESSOR: GEOGRAPHY" },
          { id: 11, title: "LABORATORY TECHNICIAN: PHYSICS" },
          { id: 12, title: "LECTURER: GEOGRAPHY" },
          { id: 13, title: "LECTURER: GEOLOGY" },
          { id: 14, title: "PROFESSOR: ANALYTICAL CHEMISTRY" },
          { id: 15, title: "SENIOR LECTURER: PHYSICAL GEOGRAPHY" },
          { id: 16, title: "Manager" },
          { id: 17, title: "Director" },
          { id: 18, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "COMPUTER SCIENCE & IT",
        description: "",
        positions: [
          { id: 0, title: "LECTURER: COMPUTER SCIENCE & INFO TECH" },
          { id: 1, title: "ACADEMIC ADVISOR" },
          { id: 2, title: "LECTURER" },
          { id: 3, title: "LECTURER: COMPUTER SCIENCE & INFO TECHS" },
          { id: 4, title: "SENIOR LECTURER: COMPUTER SCIENCES" },
          { id: 5, title: "SENIOR LECTURER:COMPUTER SCIENCES & IT" },
          { id: 6, title: "SENIOR LECTURER: COMPUTER SCIENCE AND IT" },
          { id: 7, title: "LECTURER: COMPUTER SCIENCE" },
          { id: 8, title: "ASSOCIATE PROFESSOR:COMPUTER SCIENCE&IT" },
          { id: 9, title: "LABORATORY TECHNICIAN:COMPUTER SCIENCE" },
          { id: 10, title: "LECTURER: COMPUTER SCIENCES" },
          { id: 11, title: "LECTURER: IT" },
          { id: 12, title: "LECTURER:COMPUTER SCIENCE & IT" },
          { id: 13, title: "SENIOR LECTURER: INFORMATION TECHNOLOGY" },
          { id: 14, title: "Manager" },
          { id: 15, title: "Director" },
          { id: 16, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "NATURAL & APPLIED SCIENCES",
        description: "",
        positions: [
          { id: 0, title: "LABORATORY TECHNICIAN: CHEMISTRY" },
          { id: 1, title: "LECTURER: GEOLOGY" },
          { id: 2, title: "DIRECTOR FOR GLOBAL CHANGE" },
          { id: 3, title: "LABORATORY TECHNICIAN: GEOLOGY" },
          { id: 4, title: "SENIOR ADMINISTRATOR:CGC" },
          { id: 5, title: "Manager" },
          { id: 6, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "NAS ADMIN",
        description: "",
        positions: [
          { id: 0, title: "SENIOR FACULTY ADMINISTRATOR" },
          { id: 1, title: "FACULTY ADMINISTRATOR" },
          { id: 2, title: "PERSONAL ASSISTANT:DEAN NAS" },
          { id: 3, title: "DEAN: NATURAL AND APPLIED SCIENCES" },
          { id: 4, title: "OFFICER:ADMINISTRATION" },
          { id: 5, title: "SCHOOL REGISTRAR" },
          { id: 6, title: "Manager" },
          { id: 7, title: "Director" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 5,
        name: "BIOLOGICAL & AGRI SCIENCES",
        description: "",
        positions: [
          { id: 0, title: "LECTURER: BIOLOGY & BOTANY" },
          { id: 1, title: "SENIOR LECTURER" },
          { id: 2, title: "LECTURER: AGRICULTURE (Ngap)" },
          { id: 3, title: "LECTURER: BIOLOGY & ZOOLOGY" },
          { id: 4, title: "SENIOR LECTURER: BIOLOGY & ZOOLOGY" },
          { id: 5, title: "PROFESSOR: ZOOLOGY" },
          { id: 6, title: "LAB TECHNICIAN BIO & AGRICULTURE" },
          { id: 7, title: "LABORATORY TECHNICIAN: BIOLOGY" },
          { id: 8, title: "LECTURER: BOTANY" },
          { id: 9, title: "PART TIME ACADEMIC" },
          { id: 10, title: "SENIOR LECTURER:ZOOLOGY" },
          { id: 11, title: "Manager" },
          { id: 12, title: "Director" },
          { id: 13, title: "Intern" },
        ],
      },
      {
        id: 6,
        name: "MATHEMATICAL SCIENCES",
        description: "",
        positions: [
          { id: 0, title: "SENIOR LECTURER: APPLIED MATHEMATICS" },
          { id: 1, title: "LECTURER: MATHEMATICS" },
          { id: 2, title: "LECTURER: STATISTICS" },
          { id: 3, title: "SENIOR LECTURER: STATISTICS" },
          { id: 4, title: "LECTURER: APPLIED MATHEMATICS" },
          { id: 5, title: "SENIOR LECTURER:APPLIED MATHEMATICS" },
          { id: 6, title: "PART TIME ACADEMIC" },
          { id: 7, title: "PROFESSOR:MATHEMATICS" },
          { id: 8, title: "SENIOR LECTURER: PURE MATHEMATICS" },
          { id: 9, title: "SENIOR LECTURER: STATS & OPER RESEARCH" },
          { id: 10, title: "Manager" },
          { id: 11, title: "Director" },
          { id: 12, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "DVC: ACADEMIC",
    type: "Executive",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "TEACH OUT PROGRAMME",
        description: "",
        positions: [
          { id: 0, title: "ACADEMIC FACILITATOR" },
          { id: 1, title: "OFFICER:ADMINISTRATION TLPD" },
          { id: 2, title: "nGAP Lecturer: Setswana" },
          { id: 3, title: "SENIOR MANAGER: QUALITY ASSURANCE" },
          { id: 4, title: "ACADEMIC WRITER" },
          { id: 5, title: "UCDP PROJECT MANAGER" },
          { id: 6, title: "OFFICER:QUALITY ASSURANCE" },
          { id: 7, title: "Director" },
          { id: 8, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "RESEARCH",
        description: "",
        positions: [
          { id: 0, title: "SENIOR MANAGER:POST GRADUATE AFFAIRS" },
          { id: 1, title: "SARChI Chair in Inclusive Rural Educatio" },
          { id: 2, title: "OFFICER: ADMINISTRATION" },
          { id: 3, title: "LEARNING ANALYTICS COORDINATOR" },
          { id: 4, title: "SENIOR OFFICER: RESEARCH" },
          { id: 5, title: "CENTRE ADMINISTRATOR" },
          { id: 6, title: "DIRECTOR:RESEARCH" },
          { id: 7, title: "JUNIOR LEARNING ANALYTICS" },
          { id: 8, title: "SENIOR ADMINISTRATOR:TECH TRANSFER" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "LIBRARY",
        description: "",
        positions: [
          { id: 0, title: "LIBRARIAN: COLLECTION DEVELOPMENT" },
          { id: 1, title: "LIBRARIAN: CATALOGUING/METADATA" },
          { id: 2, title: "INFORMATION LIBRARIAN" },
          { id: 3, title: "SNR LIBRARIAN: LEARNING AND RESEARCH SER" },
          { id: 4, title: "LIBRARY ADMINISTRATOR: CIRCULATION" },
          { id: 5, title: "DIRECTOR: LIBRARY & INFORMATION SERVICES" },
          { id: 6, title: "LIBRARY ASSISTANT:TECHNICAL SERVICES" },
          { id: 7, title: "LIBRARY ADMINISTRATOR:CIRCULATION" },
          { id: 8, title: "SENIOR ADMINISTRATOR:LIBRARY CIRCULATION" },
          { id: 9, title: "LIBRARIAN: SYSTEMS" },
          { id: 10, title: "OFFICER: ADMINISTRATION LIBRARY" },
          { id: 11, title: "Manager" },
          { id: 12, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "TEACHING LEARNING & PROG. DEV.",
        description: "",
        positions: [
          { id: 0, title: "OFFICER: CURRICULUM CONTENT" },
          { id: 1, title: "PROGRAMME MANAGER:E-LEARNING" },
          { id: 2, title: "OFFICER:STUDENT ACADEMIC SUPPORT" },
          { id: 3, title: "PROGRAMME MANAGER:STUDENT ACADEMIC SUPPO" },
          { id: 4, title: "PROJECT COORDINATOR FASSET" },
          { id: 5, title: "OFFICER: TLPD" },
          { id: 6, title: "ADMINISTRATOR:E-LEARNING" },
          { id: 7, title: "DIRECTOR: TEACHING LEARNING & PROG DEV" },
          { id: 8, title: "PROGRAMME MANAGER: CPD" },
          { id: 9, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "FACULTY OF EDUCATION",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "NATURAL SCIENCES TEACHING",
        description: "",
        positions: [
          { id: 0, title: "LECTURER:MATHEMATICS TEACHING" },
          { id: 1, title: "LECTURER: TEACHNOLOGY TEACHING" },
          { id: 2, title: "LECTURER: MATHEMATICS" },
          { id: 3, title: "JUNIOR LECTURER:NATURAL SCIENCE TEACHING" },
          { id: 4, title: "LABORATORY TECHNICIAN: SCIENCES" },
          { id: 5, title: "LECTURER" },
          { id: 6, title: "ASSOCIATE PROFESSOR: APPLIED MATHEMATICS" },
          { id: 7, title: "JUNIOR LECTURER: TECHNOLOGY" },
          { id: 8, title: "LECTURER: LIFE SCIENCE TEACHING" },
          { id: 9, title: "LECTURER: MATHEMATICS TEACHING" },
          { id: 10, title: "LECTURER:ICT IN EDUCATION" },
          { id: 11, title: "LECTURER:TEACHING OF NATURAL SCIENCES" },
          { id: 12, title: "LECTURER: PHYSICAL SCIENCES TEACHING" },
          { id: 13, title: "SENIOR LECTURER: NATURAL SCIENCE TEACHIN" },
          { id: 14, title: "SENIOR LECTURER: NATURAL SCIENCES TEACHI" },
          { id: 15, title: "Manager" },
          { id: 16, title: "Director" },
          { id: 17, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "EDUCATION STUDIES",
        description: "",
        positions: [
          { id: 0, title: "PART TIME ACADEMIC" },
          { id: 1, title: "LECTURER: CURRICULUM STUDIES" },
          { id: 2, title: "LECTURER: EDUCUATION & MAN STUDIES" },
          { id: 3, title: "SENIOR OFFICER: TEACHING PRACTICE" },
          { id: 4, title: "Senior Lecturer: Policy Studies" },
          { id: 5, title: "SENIOR LECTURER: FOUNDATION PHASE" },
          { id: 6, title: "SENIOR LECTURER: POLICY STUDIES" },
          { id: 7, title: "LECTURER NGAP FOUNDATION PHASE" },
          { id: 8, title: "LECTURER: TEACHING PRACTICE (nGAP)" },
          { id: 9, title: "LECTURER SETSWANA FOUNDATION PHASE" },
          { id: 10, title: "ASSOCIATE PROFESSOR: EDUCATION" },
          { id: 11, title: "SENIOR LECTURER: EDUCATION" },
          { id: 12, title: "LECTURER FOUNDATION PHASE AFRIKAANS TEA" },
          { id: 13, title: "LECTURER: FOUNDATION PHASE ENGLISH" },
          { id: 14, title: "LECTURER: INCLUSIVE EDUCATION" },
          { id: 15, title: "LECTURER: PSYCHOLOGY OF EDUCATION" },
          { id: 16, title: "LECTURER:PHILOSOPHY IN EDUCATION" },
          { id: 17, title: "PROFESSOR: PHILOSOPHY IN EDUCATION" },
          { id: 18, title: "Manager" },
          { id: 19, title: "Director" },
          { id: 20, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "EDUCATION ADMIN",
        description: "",
        positions: [
          { id: 0, title: "PART TIME ACADEMIC" },
          { id: 1, title: "DEAN OF FACULTY: EDUCATION" },
          { id: 2, title: "FACULTY MANAGER: ACADEMIC ADMINISTRATION" },
          { id: 3, title: "ADMINISTRATOR" },
          { id: 4, title: "SENIOR FACULTY ADMINISTRATOR" },
          { id: 5, title: "OFFICER:ADMINISTRATION" },
          { id: 6, title: "FACULTY ADMINISTRATOR" },
          { id: 7, title: "PERSONAL ASSISTANT:DEAN EDUCATION" },
          { id: 8, title: "Director" },
          { id: 9, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "HUMAN SCIENCES TEACHING",
        description: "",
        positions: [
          { id: 0, title: "LECTURER: ACCOUNTING & EMS TEACHING" },
          { id: 1, title: "LECTURER: AFRIKAANS TEACHING" },
          { id: 2, title: "LECTURER: ISIXHOSA" },
          { id: 3, title: "LECTURER: ECONOMICS & BUSINESS TEACHING" },
          { id: 4, title: "ASSOCIATE PROFESSOR: HISTORY & SOC SCIEN" },
          { id: 5, title: "LECTURER: SETSWANA TEACHING" },
          { id: 6, title: "LECTURER: GEOGRAPHY & SOC. SCI. TEACHING" },
          { id: 7, title: "LECTURER: ACCOUNTING TEACHING" },
          { id: 8, title: "LECTURER: ENGLISH TEACHING" },
          { id: 9, title: "LECTURER:HISTORY TEACHING" },
          { id: 10, title: "SENIOR LECTURER: GEOGRAPHY & SOC. SCI. T" },
          { id: 11, title: "Manager" },
          { id: 12, title: "Director" },
          { id: 13, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "FACULTY OF HUMANITIES",
    type: "Academic",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "LANGUAGES & COMMUNICATION",
        description: "",
        positions: [
          { id: 0, title: "LECTURER: AFRIKAANS" },
          { id: 1, title: "SENIOR LECTURER:ENGLISH" },
          { id: 2, title: "LECTURER:INTERPRETING AND TRANSLATION" },
          { id: 3, title: "LECTURER: INTERPRETING AND TRANSLATION" },
          { id: 4, title: "LECTURER: ENGLISH STUDIES" },
          { id: 5, title: "NGAP LECTURER:CREATIVE WRITING" },
          { id: 6, title: "LECTURER: ISIXHOSA" },
          { id: 7, title: "LECTURER: ENGLISH" },
          { id: 8, title: "LECTURER:SETSWANA" },
          { id: 9, title: "ASSOCIATE PROFESSOR: AFRIKAANS" },
          { id: 10, title: "SENIOR LECTURER: AFRIKAANS" },
          { id: 11, title: "LECTURER:ENGLISH" },
          { id: 12, title: "NGAP LECTURER: ISIXHOSA" },
          { id: 13, title: "LECTURER: SETSWANA" },
          { id: 14, title: "Manager" },
          { id: 15, title: "Director" },
          { id: 16, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "HUMAN & SOCIAL SCIENCES",
        description: "",
        positions: [
          { id: 0, title: "LECTURER: PSYCHOLOGY" },
          { id: 1, title: "LECTURER:SOCIOLOGY (C)" },
          { id: 2, title: "LECTURER:ANTHROPOLOGY" },
          { id: 3, title: "LECTURER: ANTHROPOLOGY" },
          { id: 4, title: "SENIOR LECTURER: HISTORY" },
          { id: 5, title: "ASSOCIATE PROFESSOR: ANTHROPOLOGY" },
          { id: 6, title: "LECTURER: PSYCHOLOGY (nGAP)" },
          { id: 7, title: "LECTURER: SOCIAL ANTHROPOLOGY" },
          { id: 8, title: "LECTURER: SOCIOLOGY" },
          { id: 9, title: "LECTURER: HISTORY" },
          { id: 10, title: "SENIOR LECTURER:PSYCHOLOGY" },
          { id: 11, title: "SENIOR LECTURER: SOCIOLOGY" },
          { id: 12, title: "SENIOR LECTURER:HISTORY" },
          { id: 13, title: "SENIOR LECTURER:SOCIOLOGY" },
          { id: 14, title: "Manager" },
          { id: 15, title: "Director" },
          { id: 16, title: "Intern" },
        ],
      },
      {
        id: 3,
        name: "HERITAGE STUDIES",
        description: "",
        positions: [
          { id: 0, title: "SENIOR LECTURER: HERITAGE STUDIES" },
          { id: 1, title: "Lecturer: Heritage Studies" },
          { id: 2, title: "LECTURER: ARCHAEOLOGY & HERITAGE STUDIES" },
          { id: 3, title: "LECTURER:HERITAGE STUDIES" },
          { id: 4, title: "ASSOCIATE PROFESSOR" },
          { id: 5, title: "LECTURER: HERITAGE STUDIES" },
          { id: 6, title: "LECTURER:ARHCAEOLOGY" },
          { id: 7, title: "SENIOR LECTURER: MATERIAL CONSERVATION" },
          { id: 8, title: "Manager" },
          { id: 9, title: "Director" },
          { id: 10, title: "Intern" },
        ],
      },
      {
        id: 4,
        name: "HUMANITIES ADMIN",
        description: "",
        positions: [
          { id: 0, title: "SENIOR FACULTY ADMINISTRATOR" },
          { id: 1, title: "PERSONAL ASSISTANT:DEAN HUMANITIES" },
          { id: 2, title: "DEAN OF FACULTY: HUMANITIES" },
          { id: 3, title: "OFFICER:ADMINISTRATION" },
          { id: 4, title: "SCHOOL REGISTRAR" },
          { id: 5, title: "LECTURER: CREATIVE WRITING" },
          { id: 6, title: "FACULTY ADMINISTRATOR" },
          { id: 7, title: "Manager" },
          { id: 8, title: "Director" },
          { id: 9, title: "Intern" },
        ],
      },
    ],
  },
  {
    faculty: "OFFICE OF THE CFO",
    type: "Executive",
    departments: [
      { id: 0, name: "" },
      {
        id: 1,
        name: "FINANCE",
        description: "",
        positions: [
          { id: 0, title: "MANAGER: FINANCIAL AID" },
          { id: 1, title: "OFFICER: PROJECT ACCOUNTING" },
          { id: 2, title: "OFFICER:PROJECT ACCOUNTING" },
          { id: 3, title: "ADMINISTRATOR: ASSETS" },
          { id: 4, title: "MANAGER:STUDENT AND DEBTOR SERVICES" },
          { id: 5, title: "ADMINISTRATOR: PAYMENTS & CREDITORS" },
          { id: 6, title: "OFFICER:CREDIT CONTROL" },
          { id: 7, title: "MANAGER:PROCUREMENT,GOODS AND SERVICES" },
          { id: 8, title: "ADMINISTRATOR: FINANCIAL AID" },
          { id: 9, title: "RESEARCH ADMINISTRATOR" },
          { id: 10, title: "OFFICER:MONITORING AND EVALUATION" },
          { id: 11, title: "OFFICER: DEBTORS & STUDENT ACCOUNTS" },
          { id: 12, title: "MANAGER: PAYROLL" },
          { id: 13, title: "ADMINISTARTOR: FINANCIAL AID" },
          { id: 14, title: "ADMINISTRATOR: RESEARCH AND PROJECT MAN" },
          { id: 15, title: "ADMINISTRATOR:DEBTORS & STUDENT ACCOUNTS" },
          { id: 16, title: "CHIEF FINANCIAL OFFICER" },
          { id: 17, title: "DIRECTOR FINANCIAL OPERATIONS" },
          { id: 18, title: "DIRECTOR:FINANCIAL PLANNING,REPORTING AN" },
          { id: 19, title: "MANAGER:BUDGET" },
          { id: 20, title: "MANAGER: COST ACCOUNTING" },
          { id: 21, title: "OFFICER: FINANCIAL AID" },
          { id: 22, title: "OFFICER: ASSETS" },
          { id: 23, title: "OFFICER:FINANCIAL AID" },
          { id: 24, title: "OFFICER:PAYROLL" },
          { id: 25, title: "PERSONAL ASSISTANT" },
          { id: 26, title: "Intern" },
        ],
      },
      {
        id: 2,
        name: "PROCUREMENT",
        description: "",
        positions: [
          { id: 0, title: "OFFICER: PROCUREMENT" },
          { id: 1, title: "ADMINISTRATOR: PAYMENTS & CREDITORS" },
          { id: 2, title: "MANAGER: CREDITORS" },
          { id: 3, title: "ADMINISTRATOR: SCM PURCHASING" },
          { id: 4, title: "DIRECTOR:SUPPLY CHAIN,CREDITORS & ASSETS" },
          { id: 5, title: "Intern" },
        ],
      },
    ],
  },
];
