export const positionList = [
  { id: 0, title: "Vice-Chancellor", category: "Executive Management", description: "Overall head of the university responsible for strategic leadership and governance." },
  { id: 1, title: "Deputy Vice-Chancellor: Academic", category: "Executive Management", description: "Oversees academic operations, teaching, and learning quality." },
  { id: 2, title: "Deputy Vice-Chancellor: Research and Innovation", category: "Executive Management", description: "Responsible for research output, innovation, and postgraduate studies." },
  { id: 3, title: "Deputy Vice-Chancellor: Institutional Support", category: "Executive Management", description: "Leads administrative and operational divisions of the university." },
  { id: 4, title: "Registrar", category: "Executive Management", description: "Manages academic administration, student records, and examinations." },
  { id: 5, title: "Chief Financial Officer", category: "Executive Management", description: "Leads financial planning, budgeting, and accounting functions." },
  { id: 6, title: "Chief Information Officer", category: "Executive Management", description: "Oversees ICT infrastructure, systems, and digital transformation." },
  { id: 7, title: "Chief Operations Officer", category: "Executive Management", description: "Responsible for campus operations, logistics, and service delivery." },
  { id: 8, title: "Executive Director: Human Resources", category: "Executive Management", description: "Leads HR strategy, policy, and workforce development." },
  { id: 9, title: "Executive Director: Finance", category: "Executive Management", description: "Leads financial strategy and accounting governance." },
  { id: 10, title: "Executive Director: ICT", category: "Executive Management", description: "Manages university IT governance and systems modernization." },
  { id: 11, title: "Dean", category: "Faculty Management", description: "Head of a faculty, responsible for academic leadership and strategy." },
  { id: 12, title: "Deputy Dean", category: "Faculty Management", description: "Supports the dean in faculty operations, teaching, and research." },
  { id: 13, title: "Head of Department (HOD)", category: "Faculty Management", description: "Leads a department, managing staff, budgets, and academic programs." },
  { id: 14, title: "School Director", category: "Faculty Management", description: "Leads an academic school or division within a faculty." },
  { id: 15, title: "Programme Coordinator", category: "Academic Management", description: "Coordinates academic programs, curriculum review, and quality assurance." },

  { id: 16, title: "Director: ICT Services", category: "Senior Management", description: "Oversees IT operations, networking, and infrastructure." },
  { id: 17, title: "Director: Human Resources", category: "Senior Management", description: "Leads HR operations, recruitment, and employee relations." },
  { id: 18, title: "Director: Finance", category: "Senior Management", description: "Manages budgeting, payroll, and financial control systems." },
  { id: 19, title: "Director: Student Affairs", category: "Senior Management", description: "Oversees student life, counselling, and co-curricular programs." },
  { id: 20, title: "Director: Library and Information Services", category: "Senior Management", description: "Manages all library services and academic information systems." },
  { id: 21, title: "Director: Marketing and Communications", category: "Senior Management", description: "Oversees branding, marketing, and public relations." },
  { id: 22, title: "Director: Legal and Compliance", category: "Senior Management", description: "Handles institutional legal matters and policy compliance." },
  { id: 23, title: "Director: Institutional Planning", category: "Senior Management", description: "Leads strategic planning, analytics, and reporting." },
  { id: 24, title: "Director: Facilities Management", category: "Senior Management", description: "Manages maintenance, building operations, and sustainability projects." },
  { id: 25, title: "Director: Research and Innovation", category: "Senior Management", description: "Coordinates research projects, ethics, and innovation." },
  { id: 26, title: "Director: Quality Assurance", category: "Senior Management", description: "Oversees academic quality and institutional performance." },
  { id: 27, title: "Director: Procurement and Supply Chain", category: "Senior Management", description: "Leads purchasing and logistics operations." },
  { id: 28, title: "Director: Security and Risk Management", category: "Senior Management", description: "Ensures campus safety and manages institutional risks." },
  { id: 29, title: "Director: Alumni Relations", category: "Senior Management", description: "Manages alumni engagement, fundraising, and donor relations." },
  { id: 30, title: "Director: Sport and Recreation", category: "Senior Management", description: "Oversees sports facilities and student recreation programs." },
  { id: 31, title: "Director: Campus Health Services", category: "Senior Management", description: "Manages university medical and counselling services." },
  { id: 32, title: "Senior Director: Operations", category: "Senior Management", description: "Leads cross-campus operational coordination and logistics." },
  { id: 33, title: "Senior Director: Academic Affairs", category: "Senior Management", description: "Oversees teaching and learning development initiatives." },
  { id: 34, title: "Senior Director: Corporate Affairs", category: "Senior Management", description: "Handles stakeholder relations and corporate communications." },

  { id: 35, title: "Professor", category: "Academic", description: "Senior academic with extensive research and teaching experience." },
  { id: 36, title: "Associate Professor", category: "Academic", description: "Experienced academic with leadership in research and teaching." },
  { id: 37, title: "Senior Lecturer", category: "Academic", description: "Teaches and supervises research within a discipline." },
  { id: 38, title: "Lecturer", category: "Academic", description: "Delivers lectures and supervises students." },
  { id: 39, title: "Junior Lecturer", category: "Academic", description: "Supports senior staff in teaching and assessment." },
  { id: 40, title: "Researcher", category: "Academic", description: "Conducts research in line with institutional priorities." },
  { id: 41, title: "Postdoctoral Research Fellow", category: "Academic", description: "Performs postdoctoral research and academic publications." },
  { id: 42, title: "Tutor", category: "Academic Support", description: "Provides academic support in specific modules." },
  { id: 43, title: "Teaching Assistant", category: "Academic Support", description: "Assists lecturers with marking and tutorials." },

  { id: 44, title: "Senior Manager", category: "Management", description: "Supervises operations within a functional unit." },
  { id: 45, title: "Manager", category: "Management", description: "Manages a department or service area." },
  { id: 46, title: "Assistant Manager", category: "Management", description: "Supports management functions and coordinates teams." },
  { id: 47, title: "Operations Manager", category: "Management", description: "Handles daily operational and logistics activities." },
  { id: 48, title: "Project Manager", category: "Management", description: "Manages institutional or research projects." },

  { id: 49, title: "Senior Officer", category: "Professional", description: "Handles high-level technical or administrative duties." },
  { id: 50, title: "Officer", category: "Professional", description: "Performs professional duties in finance, HR, or ICT." },
  { id: 51, title: "Administrator", category: "Professional", description: "Handles clerical and operational administrative work." },
  { id: 52, title: "Senior Administrator", category: "Professional", description: "Supervises admin staff and manages complex processes." },
  { id: 53, title: "Administrative Assistant", category: "Professional Support", description: "Provides direct administrative support to managers." },
  { id: 54, title: "Procurement Officer", category: "Professional", description: "Oversees purchasing and tendering processes." },
  { id: 55, title: "Finance Officer", category: "Professional", description: "Handles financial operations and reporting." },
  { id: 56, title: "ICT Technician", category: "Technical Support", description: "Provides technical and systems support." },
  { id: 57, title: "Network Administrator", category: "Technical Support", description: "Manages and monitors the institutional network." },
  { id: 58, title: "Systems Analyst", category: "Technical Support", description: "Analyzes and improves information systems." },
  { id: 59, title: "Database Administrator", category: "Technical Support", description: "Manages databases and institutional data integrity." },
  { id: 60, title: "ICT Support Officer", category: "Technical Support", description: "Assists users with ICT troubleshooting and queries." },

  { id: 61, title: "Student Counsellor", category: "Student Support", description: "Provides academic and psychological counselling." },
  { id: 62, title: "Residence Warden", category: "Student Support", description: "Manages student housing and disciplinary matters." },
  { id: 63, title: "Student Affairs Officer", category: "Student Support", description: "Coordinates student engagement programs." },
  { id: 64, title: "Peer Mentor", category: "Student Support", description: "Guides and supports first-year students." },
  { id: 65, title: "Career Development Officer", category: "Student Support", description: "Provides career guidance and job placement support." },

  { id: 66, title: "Health Practitioner", category: "Health Services", description: "Provides medical and wellness services." },
  { id: 67, title: "Nurse", category: "Health Services", description: "Delivers clinical and occupational health care." },
  { id: 68, title: "Psychologist", category: "Health Services", description: "Offers psychological assessment and therapy." },

  { id: 69, title: "Librarian", category: "Library and Information Services", description: "Manages library collections and assists researchers." },
  { id: 70, title: "Senior Librarian", category: "Library and Information Services", description: "Leads library operations and digital resource management." },
  { id: 71, title: "Library Assistant", category: "Library and Information Services", description: "Provides library support and circulation services." },

  { id: 72, title: "Communications Officer", category: "Marketing and Communications", description: "Manages communication strategies and media content." },
  { id: 73, title: "Marketing Officer", category: "Marketing and Communications", description: "Promotes university programs and events." },
  { id: 74, title: "Graphic Designer", category: "Marketing and Communications", description: "Designs branding and publication material." },
  { id: 75, title: "Photographer/Videographer", category: "Marketing and Communications", description: "Captures and edits multimedia content." },

  { id: 76, title: "Legal Advisor", category: "Legal and Compliance", description: "Provides legal guidance and ensures institutional compliance." },
  { id: 77, title: "Internal Auditor", category: "Governance and Compliance", description: "Audits systems for transparency and accountability." },
  { id: 78, title: "Quality Assurance Officer", category: "Governance and Compliance", description: "Monitors academic and administrative standards." },
  { id: 79, title: "Research Ethics Officer", category: "Governance and Compliance", description: "Oversees research integrity and compliance." },
];
