export const positionList = [
  { id: 0, title: "Vice-Chancellor", category: "Executive Management", description: "Overall head of the university responsible for strategic leadership and governance." },
  { id: 1, title: "Deputy Vice-Chancellor: Academic", category: "Executive Management", description: "Oversees academic operations, teaching, and learning quality." },
  { id: 2, title: "Deputy Vice-Chancellor: Research and Innovation", category: "Executive Management", description: "Responsible for research output, innovation, and postgraduate studies." },
  { id: 3, title: "Deputy Vice-Chancellor: Institutional Support", category: "Executive Management", description: "Leads administrative and operational divisions of the university." },
  { id: 4, title: "Registrar", category: "Executive Management", description: "Manages academic administration, student records, and examinations." },
  { id: 5, title: "Chief Financial Officer", category: "Executive Management", description: "Leads financial planning, budgeting, and accounting functions." },
  { id: 6, title: "Chief Operations Officer", category: "Executive Management", description: "Responsible for campus operations, logistics, and service delivery." },
  { id: 7, title: "Chief Information Officer", category: "Executive Management", description: "Oversees ICT infrastructure, systems, and digital transformation." },
  { id: 8, title: "Executive Director: Human Resources", category: "Executive Management", description: "Leads HR strategy, policy, and workforce development." },
  { id: 9, title: "Executive Director: Finance", category: "Executive Management", description: "Leads financial strategy and accounting governance." },
  { id: 10, title: "Executive Director: ICT", category: "Executive Management", description: "Manages university IT governance and systems modernization." },

  { id: 11, title: "Dean: Faculty of Humanities", category: "Faculty Management", description: "Head of the faculty, responsible for academic leadership and strategy." },
  { id: 12, title: "Dean: Faculty of Natural and Applied Sciences", category: "Faculty Management", description: "Head of the faculty, responsible for academic leadership and strategy." },
  { id: 13, title: "Dean: Faculty of Education", category: "Faculty Management", description: "Head of the faculty, responsible for academic leadership and strategy." },
  { id: 14, title: "Dean: Faculty of Economic and Management Sciences", category: "Faculty Management", description: "Head of the faculty, responsible for academic leadership and strategy." },
  { id: 15, title: "Deputy Dean", category: "Faculty Management", description: "Supports the dean in faculty operations, teaching, and research." },
  { id: 16, title: "Head of Department (HOD)", category: "Faculty Management", description: "Leads a department, managing staff, budgets, and academic programs." },
  { id: 17, title: "School Director", category: "Faculty Management", description: "Leads an academic school or division within a faculty." },
  { id: 18, title: "Programme Coordinator", category: "Academic Management", description: "Coordinates academic programs, curriculum review, and quality assurance." },

  { id: 19, title: "Professor: Heritage Studies", category: "Academic", description: "Senior academic in Heritage Studies with extensive research and teaching experience." },
  { id: 20, title: "Professor: Economics", category: "Academic", description: "Senior academic in Economics with extensive research and teaching experience." },
  { id: 21, title: "Professor: Philosophy in Education", category: "Academic", description: "Senior academic in Philosophy of Education with extensive research and teaching experience." },
  { id: 22, title: "Professor: Mathematics", category: "Academic", description: "Senior academic in Mathematics with extensive research and teaching experience." },
  { id: 23, title: "Professor: Zoology", category: "Academic", description: "Senior academic in Zoology with extensive research and teaching experience." },
  { id: 24, title: "Professor: Education Studies", category: "Academic", description: "Senior academic in Education Studies with extensive research and teaching experience." },

  { id: 25, title: "Associate Professor: Afrikaans", category: "Academic", description: "Experienced academic in Afrikaans with leadership in research and teaching." },
  { id: 26, title: "Associate Professor: Physics", category: "Academic", description: "Experienced academic in Physics with leadership in research and teaching." },
  { id: 27, title: "Associate Professor: Management", category: "Academic", description: "Experienced academic in Management with leadership in research and teaching." },
  { id: 28, title: "Associate Professor: Accounting and Finance", category: "Academic", description: "Experienced academic in Accounting and Finance with leadership in research and teaching." },
  { id: 29, title: "Associate Professor: Anthropology", category: "Academic", description: "Experienced academic in Anthropology with leadership in research and teaching." },
  { id: 30, title: "Associate Professor: Computer Science & IT", category: "Academic", description: "Experienced academic in Computer Science & IT with leadership in research and teaching." },
  { id: 31, title: "Associate Professor: Applied Mathematics", category: "Academic", description: "Experienced academic in Applied Mathematics with leadership in research and teaching." },

  { id: 32, title: "Senior Lecturer: Sociology", category: "Academic", description: "Teaches and supervises research in Sociology." },
  { id: 33, title: "Senior Lecturer: Retail Management", category: "Academic", description: "Teaches and supervises research in Retail Management." },
  { id: 34, title: "Senior Lecturer: Education", category: "Academic", description: "Teaches and supervises research in Education." },
  { id: 35, title: "Senior Lecturer: Heritage Studies", category: "Academic", description: "Teaches and supervises research in Heritage Studies." },
  { id: 36, title: "Senior Lecturer: Natural Science Teaching", category: "Academic", description: "Teaches and supervises research in Natural Science Teaching." },
  { id: 37, title: "Senior Lecturer: Applied Mathematics", category: "Academic", description: "Teaches and supervises research in Applied Mathematics." },
  { id: 38, title: "Senior Lecturer: Computer Science & IT", category: "Academic", description: "Teaches and supervises research in Computer Science & IT." },
  { id: 39, title: "Senior Lecturer: Physical Chemistry", category: "Academic", description: "Teaches and supervises research in Physical Chemistry." },
  { id: 40, title: "Senior Lecturer: Policy Studies", category: "Academic", description: "Teaches and supervises research in Policy Studies." },
  { id: 41, title: "Senior Lecturer: Foundation Phase", category: "Academic", description: "Teaches and supervises research in Foundation Phase Education." },

  { id: 42, title: "Lecturer: Creative Writing", category: "Academic", description: "Delivers lectures and supervises students in Creative Writing." },
  { id: 43, title: "Lecturer: Life Science Teaching", category: "Academic", description: "Delivers lectures and supervises students in Life Science Teaching." },
  { id: 44, title: "Lecturer: Geography", category: "Academic", description: "Delivers lectures and supervises students in Geography." },
  { id: 45, title: "Lecturer: Accounting", category: "Academic", description: "Delivers lectures and supervises students in Accounting." },
  { id: 46, title: "Lecturer: Psychology", category: "Academic", description: "Delivers lectures and supervises students in Psychology." },
  { id: 47, title: "Lecturer: Teaching of Natural Sciences", category: "Academic", description: "Delivers lectures and supervises students in Teaching of Natural Sciences." },
  { id: 48, title: "Lecturer: Computer Science & IT", category: "Academic", description: "Delivers lectures and supervises students in Computer Science & IT." },
  { id: 49, title: "Lecturer: Entrepreneurship", category: "Academic", description: "Delivers lectures and supervises students in Entrepreneurship." },
  { id: 50, title: "Lecturer: Biology & Zoology", category: "Academic", description: "Delivers lectures and supervises students in Biology and Zoology." },
  { id: 51, title: "Lecturer: Mathematics Teaching", category: "Academic", description: "Delivers lectures and supervises students in Mathematics Teaching." },
  { id: 52, title: "Lecturer: Business Management", category: "Academic", description: "Delivers lectures and supervises students in Business Management." },
  { id: 53, title: "Lecturer: Economics & Business Teaching", category: "Academic", description: "Delivers lectures and supervises students in Economics and Business Teaching." },
  { id: 54, title: "Lecturer: Philosophy in Education", category: "Academic", description: "Delivers lectures and supervises students in Philosophy in Education." },
  { id: 55, title: "Lecturer: Setswana Teaching", category: "Academic", description: "Delivers lectures and supervises students in Setswana." },
  { id: 56, title: "Lecturer: Inclusive Education", category: "Academic", description: "Delivers lectures and supervises students in Inclusive Education." },
  { id: 57, title: "Lecturer: Applied Mathematics", category: "Academic", description: "Delivers lectures and supervises students in Applied Mathematics." },
  { id: 58, title: "Lecturer: English Teaching", category: "Academic", description: "Delivers lectures and supervises students in English Teaching." },
  { id: 59, title: "Junior Lecturer: Communication", category: "Academic", description: "Supports senior staff in teaching and assessment in Communication." },
  { id: 60, title: "Junior Lecturer: Natural Science Teaching", category: "Academic", description: "Supports senior staff in teaching and assessment in Natural Science." },
  { id: 61, title: "Junior Lecturer: Technology", category: "Academic", description: "Supports senior staff in teaching and assessment in Technology." },
  { id: 62, title: "Junior Lecturer: Work Integrated Learning", category: "Academic", description: "Supports senior staff in teaching and assessment in Work Integrated Learning." },

  { id: 63, title: "Postdoctoral Research Fellow", category: "Academic", description: "Performs postdoctoral research and academic publications." },
  { id: 64, title: "Tutor", category: "Academic Support", description: "Provides academic support in specific modules." },
  { id: 65, title: "Teaching Assistant", category: "Academic Support", description: "Assists lecturers with marking and tutorials." },
  { id: 66, title: "Academic Facilitator", category: "Academic Support", description: "Supports teaching, curriculum delivery, and student learning activities." },
  { id: 67, title: "Academic Advisor", category: "Academic Support", description: "Provides guidance and academic planning support for students." },
  { id: 68, title: "Programme Manager: Quality Assurance", category: "Management", description: "Manages quality assurance programs and academic standards." },
  { id: 69, title: "Project Manager", category: "Management", description: "Manages institutional or research projects." },
  { id: 70, title: "Manager: HR Operations", category: "Management", description: "Manages human resources operations and staff development." },
  { id: 71, title: "Senior Manager", category: "Management", description: "Supervises operations within a functional unit." },
  { id: 72, title: "Manager", category: "Management", description: "Manages a department or service area." },
  { id: 73, title: "Operations Manager", category: "Management", description: "Handles daily operational and logistics activities." },
  { id: 74, title: "Cluster Coordinator", category: "Management", description: "Coordinates activities and staff within a cluster or division." },

  { id: 75, title: "Officer", category: "Professional", description: "Performs professional duties in finance, HR, or ICT." },
  { id: 76, title: "Senior Officer", category: "Professional", description: "Handles high-level technical or administrative duties." },
  { id: 77, title: "Administrator", category: "Professional", description: "Handles clerical and operational administrative work." },
  { id: 78, title: "Senior Administrator", category: "Professional", description: "Supervises admin staff and manages complex processes." },
  { id: 79, title: "Administrative Assistant", category: "Professional Support", description: "Provides direct administrative support to managers." },
  { id: 80, title: "Research Administrator", category: "Professional", description: "Supports research project administration and reporting." },
  { id: 81, title: "Project Coordinator FASSET", category: "Professional", description: "Coordinates FASSET-related projects and initiatives." },

  { id: 82, title: "ICT Technician", category: "Technical Support", description: "Provides technical and systems support." },
  { id: 83, title: "Network Administrator", category: "Technical Support", description: "Manages and monitors the institutional network." },
  { id: 84, title: "Systems Analyst", category: "Technical Support", description: "Analyzes and improves information systems." },
  { id: 85, title: "Database Administrator", category: "Technical Support", description: "Manages databases and institutional data integrity." },
  { id: 86, title: "ICT Support Officer", category: "Technical Support", description: "Assists users with ICT troubleshooting and queries." },
  { id: 87, title: "Student Counsellor", category: "Student Support", description: "Provides academic and psychological counselling." },
  { id: 88, title: "Residence Warden", category: "Student Support", description: "Manages student housing and disciplinary matters." },
  { id: 89, title: "Student Affairs Officer", category: "Student Support", description: "Coordinates student engagement programs." },
  { id: 90, title: "Peer Mentor", category: "Student Support", description: "Guides and supports first-year students." },
  { id: 91, title: "Career Development Officer", category: "Student Support", description: "Provides career guidance and job placement support." },
  { id: 92, title: "Health Practitioner", category: "Health Services", description: "Provides medical and wellness services." },
  { id: 93, title: "Nurse", category: "Health Services", description: "Delivers clinical and occupational health care." },
  { id: 94, title: "Psychologist", category: "Health Services", description: "Offers psychological assessment and therapy." },
  { id: 95, title: "Librarian", category: "Library and Information Services", description: "Manages library collections and assists researchers." },
  { id: 96, title: "Senior Librarian", category: "Library and Information Services", description: "Leads library operations and digital resource management." },
  { id: 97, title: "Library Assistant", category: "Library and Information Services", description: "Provides library support and circulation services." },
  { id: 98, title: "Communications Officer", category: "Marketing and Communications", description: "Manages communication strategies and media content." },
  { id: 99, title: "Marketing Officer", category: "Marketing and Communications", description: "Promotes university programs and events." },
  { id: 100, title: "Graphic Designer", category: "Marketing and Communications", description: "Designs branding and publication material." },
  { id: 101, title: "Photographer/Videographer", category: "Marketing and Communications", description: "Captures and edits multimedia content." },
  { id: 102, title: "Legal Advisor", category: "Legal and Compliance", description: "Provides legal guidance and ensures institutional compliance." },
  { id: 103, title: "Internal Auditor", category: "Governance and Compliance", description: "Audits systems for transparency and accountability." },
  { id: 104, title: "Quality Assurance Officer", category: "Governance and Compliance", description: "Monitors academic and administrative standards." },
  { id: 105, title: "Research Ethics Officer", category: "Governance and Compliance", description: "Ensures ethical standards are maintained in research." },
  { id: 106, title: "Coach", category: "Sports & Recreation", description: "Trains and develops student athletes in specific sports." },
  { id: 107, title: "Manager: Sport & Recreation", category: "Sports & Recreation", description: "Oversees sports facilities, teams, and student recreation programs." },
  { id: 108, title: "Athletics and Gym Manager", category: "Sports & Recreation", description: "Manages athletics programs and gym facilities." },
  { id: 109, title: "Strength and Conditioning Coach", category: "Sports & Recreation", description: "Provides fitness and conditioning training to athletes." },
  { id: 110, title: "Physiotherapist", category: "Sports & Recreation", description: "Provides physical therapy and rehabilitation to athletes." },
  { id: 111, title: "Coach: Volleyball", category: "Sports & Recreation", description: "Trains the volleyball team and develops players’ skills." },
  { id: 112, title: "Coach: Tennis", category: "Sports & Recreation", description: "Trains the tennis team and develops players’ skills." },
  { id: 113, title: "Coach: Hockey", category: "Sports & Recreation", description: "Trains the hockey team and develops players’ skills." },
  { id: 114, title: "Coach: Football", category: "Sports & Recreation", description: "Trains the football team and develops players’ skills." },
  { id: 115, title: "Coach: Table Tennis", category: "Sports & Recreation", description: "Trains the table tennis team and develops players’ skills." },
  { id: 116, title: "Coach: Cricket", category: "Sports & Recreation", description: "Trains the cricket team and develops players’ skills." },
  { id: 117, title: "Coach: Basketball", category: "Sports & Recreation", description: "Trains the basketball team and develops players’ skills." },
  { id: 118, title: "Coach: Dance & Aerobics", category: "Sports & Recreation", description: "Trains students in dance and aerobics activities." },
  { id: 119, title: "Coach: Rugby", category: "Sports & Recreation", description: "Trains the rugby team and develops players’ skills." },
  { id: 120, title: "Coach: Cheerleading", category: "Sports & Recreation", description: "Trains the cheerleading team and develops routines." },

  { id: 121, title: "Administrator", category: "Administration", description: "Handles clerical, operational, and general administrative work." },
  { id: 122, title: "Senior Administrator", category: "Administration", description: "Supervises administrative staff and manages complex processes." },
  { id: 123, title: "Administrative Assistant", category: "Administration", description: "Provides direct administrative support to managers or departments." },
  { id: 124, title: "Administrative Officer", category: "Administration", description: "Manages office operations and supports administrative procedures." },
  { id: 125, title: "Programme Manager", category: "Administration", description: "Oversees program implementation, coordination, and reporting." },
  { id: 126, title: "Project Manager", category: "Administration", description: "Manages institutional or research projects, budgets, and teams." },
  { id: 127, title: "Project Coordinator", category: "Administration", description: "Coordinates project activities, reporting, and logistics." },
  { id: 128, title: "Personal Assistant", category: "Administration", description: "Provides support and coordination for executives or managers." },
  { id: 129, title: "Personal Assistant: Dean/VC", category: "Administration", description: "Provides dedicated administrative support to faculty or executive leadership." },
  { id: 130, title: "Manager", category: "Management", description: "Manages a department, functional unit, or service area." },
  { id: 131, title: "Senior Manager", category: "Management", description: "Oversees broader operational or administrative units." },
  { id: 132, title: "Assistant Manager", category: "Management", description: "Supports management functions and team coordination." },
  { id: 133, title: "Operations Manager", category: "Management", description: "Handles daily operational and logistical activities." },
  { id: 134, title: "Manager: HR Operations", category: "Management", description: "Oversees human resource processes and employee relations." },
  { id: 135, title: "Manager: Finance/Payroll", category: "Management", description: "Manages finance, payroll, and accounting operations." },
  { id: 136, title: "Manager: Student & Academic Services", category: "Management", description: "Oversees student support services and academic administration." },
  { id: 137, title: "Officer: Administration", category: "Professional", description: "Performs professional administrative duties within departments." },
  { id: 138, title: "Officer: HR/Finance/Procurement", category: "Professional", description: "Handles operational and professional responsibilities in HR, finance, or procurement." },
  { id: 139, title: "Officer: Project/Monitoring", category: "Professional", description: "Coordinates projects, monitoring, and evaluation activities." },
  { id: 140, title: "Officer: Sport/Facilities", category: "Professional", description: "Manages sports, recreational, or facilities support operations." },
  { id: 141, title: "Officer: Career/Student Development", category: "Professional", description: "Supports student career guidance and personal development programs." },
  { id: 142, title: "Supervisor: Cleaning/Support Services", category: "Support Services", description: "Oversees cleaning, maintenance, and support service staff." },
  { id: 143, title: "General Assistant", category: "Support Services", description: "Performs general support tasks across campus facilities." },
  { id: 144, title: "Maintenance Assistant", category: "Support Services", description: "Provides assistance in facility maintenance and repairs." },
  { id: 145, title: "Laboratory Technician", category: "Technical Support", description: "Supports laboratory activities in sciences and research." },
  { id: 146, title: "Senior Laboratory Technician", category: "Technical Support", description: "Leads laboratory operations and supervises technical staff." },
  { id: 147, title: "Maker Space Technical Assistant", category: "Technical Support", description: "Supports technical activities in innovation labs or maker spaces." },
  { id: 148, title: "IT Support Technician", category: "Technical Support", description: "Provides troubleshooting, hardware, and software support to users." },
  { id: 149, title: "Network Engineer", category: "Technical Support", description: "Designs and maintains institutional network infrastructure." },
  { id: 150, title: "Information Security Analyst", category: "Technical Support", description: "Ensures institutional cybersecurity and data protection." },
  { id: 151, title: "Data Controller", category: "Professional", description: "Manages institutional data, integrity, and reporting systems." },
  { id: 152, title: "Academic Advisor", category: "Academic Support", description: "Provides academic guidance and mentoring to students." },
  { id: 153, title: "Academic Facilitator", category: "Academic Support", description: "Supports teaching and learning delivery, tutorial sessions, and curriculum implementation." },
  { id: 154, title: "Teaching Assistant", category: "Academic Support", description: "Assists lecturers with teaching, marking, and tutorials." },
  { id: 155, title: "Programme Coordinator/Manager", category: "Academic Support", description: "Coordinates academic programs and ensures quality compliance." },
  { id: 156, title: "Research Administrator", category: "Professional", description: "Manages research administration, ethics, and funding support." },
  { id: 157, title: "Academic Writer", category: "Academic Support", description: "Supports research and academic publications through writing and editing." },
];
